filewatcher/filewatcher.go, filewatcher/filewatcher_test.go
Also fix a bug of storing nil value when parser fails, and add a test
case for that.
=> filewatcher: Use atomic.Value instead of lock

.drone.yml
I am adding the `-race` flag for tests to test for data races in our code. Looks like we have a data race already but I have problems fixing it. It's because to the data field writes are reads are concurrent.
Given that, I wonder if it makes sense to make the locking more fine granular around writing the data here. Is it necessary to have the lock during the I/O operation? https://github.com/reddit/baseplate.go/blob/master/filewatcher/filewatcher.go#L84-L102
```
==================
WARNING: DATA RACE
Read at 0x00c0000120f0 by goroutine 8:
github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcher()
/home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:42 +0x50c
testing.tRunner()
/usr/local/go/src/testing/testing.go:909 +0x199
Previous write at …
```
=> Test for data races and fix data race in filewatcher

go.mod, go.sum, metricsbp/doc.go, metricsbp/example_nil_check_test.go, metricsbp/nil_check.go, metricsbp/nil_check_test.go, metricsbp/statsd.go, metricsbp/statsd_test.go
It provides a statsd based metrics implementation (based on go-kit), and
also related helper functions.
=> Add metricsbp package

mqsend/doc.go, mqsend/interface.go, mqsend/mqsend_linux.go, mqsend/mqsend_other.go
- Make sure we have proper line breaks on the package doc.
- Make sure we have a consistent doc for OpenMessageQueue on linux and
non-linux systems.
=> mqsend: Godoc updates

signing/doc.go, signing/doc_test.go, signing/interface.go, signing/v1.go, signing/v1_quick_test.go, signing/v1_test.go, signing/versions.go
https://github.com/reddit/baseplate.go/issues/6
~This PR depends on https://github.com/reddit/baseplate.go/pull/30, reviewers can skip the first commit.~
=> Add signing package

batcherror/batch.go, batcherror/batch_test.go, batcherror/doc.go, batcherror/doc_test.go, secrets/errors.go, secrets/secrets.go, secrets/secrets_test.go
The package is mainly ported from my previous work, with some cleanups.
Also change secrets.Document.Validate to return BatchError instead of
ValidationError, and some other error cleanups in secrets package.
=> Add batcherror package

LICENSE
=> Change our 3rd clause to standard BSD-3-Clause text

httpbp/doc.go, httpbp/example_headers_test.go, httpbp/example_response_test.go, httpbp/headers.go, httpbp/headers_test.go, httpbp/response.go, httpbp/response_test.go, httpbp/trust_handers.go, httpbp/trust_handlers_test.go
This package provides Baseplate specific helpers and integrations for http services using go-kit.
=> Add 'httpbp' package

edgecontext/edgecontext.go, edgecontext/edgecontext_test.go, edgecontext/example_middlewares_test.go, edgecontext/middlewares.go, edgecontext/middlewares_test.go, httpbp/headers.go, httpbp/headers_test.go, httpbp/trust_handlers_test.go, tracing/example_middlewares_test.go, tracing/http.go, tracing/http_test.go, tracing/middlewares.go
Finish up the remaining tasks in #69
=> Finish HTTP integrations

thriftpool/interface.go, thriftpool/ttl_client.go, thriftpool/ttl_client_test.go
Our test shows that using TTL with thriftpool will improve the
performance. I'll add a full example for this package after we
successfully deployed it to the prod.
=> thriftpool: Add TTLClient

experiments/experiments.go, experiments/experiments_test.go, timebp/second_f.go, timebp/second_f_test.go
Also switch experiments.ExperimentConfig's timestamp json types to
TimestampSecondF.
=> timebp: Add TimestampSecondF type

thriftclient/client_pool.go
- Add DefaultPoolGaugeInterval to avoid panic
- Add a few clientpool.Pool API into thriftclient.ClientPool as
otherwise the callers don't have access to them
=> thriftclient: ClientPool API changes

metricsbp/baseplate_hooks.go
Make it obvious that CreateServerSpanHook.Metrics is optional, and
unexport fields in spanHook as the type is unexported.
=> metricsbp: Span hook cleanup

Makefile, WORKSPACE, filewatcher/filewatcher_test.go, metricsbp/timer_test.go
I'm trying to put 3 commits in the same PR because they are all fairy small, reviewers can review them one by one. They will be merged separately in the end instead of squashing.
=> Tests related changes

edgecontext/BUILD.bazel, edgecontext/edgecontext_test.go, edgecontext/oauth_client.go, edgecontext/req_context.go, edgecontext/user.go, experiments/BUILD.bazel, experiments/doc.go, experiments/experiments.go
This fixes https://github.com/reddit/baseplate.go/issues/33.
Also a few small updates to experiments package that's related to this.
=> edgecontext: Add UpdateExperimentEvent implementation

thriftbp/example_server_test.go, thriftbp/server.go
=> thriftbp: Rename NewThriftServer -> NewServer

edgecontext/edgecontext.go, edgecontext/req_context.go, edgecontext/validator.go, filewatcher/doc_test.go, filewatcher/filewatcher.go, log/wrapper.go, tracing/hooks.go, tracing/span.go, tracing/tracer.go
Also add FallbackWrapper for nil-safe usage of it.
=> log: More detailed doc around Wrapper interface

README.md, clientpool/doc.go, doc.go, httpbp/doc.go, httpbp/handler.go, log/doc.go, metricsbp/doc.go, randbp/doc.go, redisbp/example_hooks_test.go, redisbp/monitored_client.go, thriftbp/client_middlewares.go, thriftbp/client_pool.go, tracing/tracer.go
Mainly fix the formatting on ordered/unordered lists in doc comments,
but also some other fixes.
=> Doc comments cleanup

log/BUILD.bazel, log/kit_wrapper_test.go, log/log_test.go
Also remove an irrelevant test.
=> log: Add cheatcode to make sure KitLogger works

baseplate.go, doc.go, httpbp/example_server_test.go, thriftbp/example_server_test.go
Also some minor tweaks:
- Add/fix comments for ExampleNewBaseplateServer functions
- Timeout could be negative, use > 0 instead of != 0
This fixes https://github.com/reddit/baseplate.go/issues/102.
=> Add links to the thrift/http examples from top doc.go

baseplate.go
The intention here is to make it clear what this method does, it isn't doing anything particularly tricky but it can be a little confusing, especially if you are new to Go.
=> Add more comments to 'baseplate.Serve'

metricsbp/baseplate_hooks_test.go, metricsbp/sampled_test.go, metricsbp/statsd.go, metricsbp/statsd_test.go
The two commits in this PR will be merged separately, so in case we need to export `Statsd.Statsd` again in the future, we can just revert that one commit.
=> Metricsbp custom rate

.bazelrc, .drone.yml, WORKSPACE
Upgrade:
- go to 1.14.3
- bazel to 3.1.0
- rules_go to 0.23.1
- gazelle to 0.21.0
=> Upgrade build/CI system

edgecontext/req_context.go
1. Use logger in Impl instead of hardcoded error level
2. Don't log empty jwt errors, as they are considered normal
=> edgecontext: Log fix for token validation

edgecontext/user.go
This is essentially the same as edgecontext.User.UpdateExperimentEvents,
but in a different format suitable for experiments.Variant call.
=> Add edgecontext.User.VariantInputs

.drone.yml, WORKSPACE, scripts/bazel_cleanup.sh
Also upgrade bazel to 3.2.0 and bazel rule packages.
=> Upgrade go to 1.14.4

thriftbp/client_middlewares.go
Add another MonitorClient before retry client middleware, with
".wrapped" suffix added to the service slug, so we have a view of the
total requests/failures/latency for all retries grouped together, from
the client's point of view.
=> thriftbp: Double MonitorClient middleware by default

experiments/experiments.go, experiments/experiments_test.go
This could be caused by empty loids. We consider them expected and they
usually need to be handled differently from other errors.
=> experiments: Return special error for empty/nil bucket key

experiments/experiments.go, experiments/experiments_test.go, experiments/variants.go
This PR addresses #250
User bucketing is currently broken. See https://github.com/reddit/baseplate.go/commit/e603bb3f46e897d02cd53acdac828ea057d23634 for the reproduction.
=> Fix experiments bucketing

breakerbp/BUILD.bazel, experiments/experiments_test.go, go.mod, go.sum
These are some stuff we missed from code review from the last 2 PRs:
- https://github.com/reddit/baseplate.go/pull/248
- https://github.com/reddit/baseplate.go/pull/249
=> Fixups from previous 2 commits

runtimebp/cpu.go
I forgot to do this before v0.5.1 release 🤦
=> runtimebp: Update comment on when the shares fallback could happen

.drone.yml, WORKSPACE
=> Upgrade go to 1.14.6

README.md, internal/gen-go/reddit/baseplate/baseplate.go, thriftbp/client_middlewares_test.go, thriftbp/example_client_test.go, thriftbp/example_server_test.go, thriftbp/thrifttest/server.go, thriftbp/thrifttest/server_test.go
Reference thrift change on Baseplate.py:
https://github.com/reddit/baseplate.py/commit/499295cd66af3cd5debd0547204f8ffcbbed730a
=> Upgrade to BaseplateServiceV2

experiments/variants_test.go, scripts/linters.sh
We already asked people to run gofmt -s in the style guide, might as
well enforce that.
Also fix the file violating it.
=> Change linters.sh to run gofmt -s

external.bzl, go.mod, go.sum
This fixes a bug upstream:
https://issues.apache.org/jira/browse/THRIFT-5257
=> Upgrade thrift

log/sentry.go
In k8s world hostname is by default the pod name, so this could be
useful to see if an issue is widespread or isolated on a single pod.
=> log: Auto report hostname tag in sentry

breakerbp/failure_ratio.go
This allows you to use the circuit breaker logic in other implementations than just the Thrift middleware it provides
=> breakerbp: Add an Execute method to FailureRatioBreaker

randbp/BUILD.bazel, randbp/string.go, randbp/string_example_test.go, randbp/string_test.go
Also add an unit test to make sure of it.
=> randbp: Fix typed nil error

.drone.yml, WORKSPACE, external.bzl, go.mod
Also upgrade bazel rule dependencies.
=> Upgrade go to 1.15.1

baseplate.go
Just a few typo fixes, mostly to comments and to one struct tag.
=> Typo fixes

metricsbp/statsd.go
It's been running in production for a few days without a problem, so
make 4096 the default.
=> metricsbp: Set DefaultBufferSize to 4096

thriftbp/client_middlewares.go, thriftbp/client_pool.go, thriftbp/errors.go, thriftbp/errors_test.go, thriftbp/server.go, thriftbp/server_middlewares.go
And use that as the default one in server and client middlewares.
=> thriftbp: Implement IDLExceptionSuppressor

errorsbp/doc.go, thriftbp/errors.go
Also some small cleanups in mainly comments following the previous
commit. I thought you can't new an interface in Go but apparently you
can.
=> errorsbp: Fix a bug in the package doc's example code

thriftbp/client_middlewares.go
This is one comment missed during 33a2c6e.
=> thriftbp: Update comment

thriftbp/client_pool.go
This fixes a bug introduced in 8354a04 causing us to never close broken
connections and always return them back to the pool.
Also take advantage of the newly added TException types to help
determine whether to close the connection or return to the pool.
=> thriftbp: Fix client pool bug

thriftbp/client_pool.go
The bug fixed in 6bfad2e highlights the fact that this is a part of the
code that has very limited external visibility, and when a bug happens
there it's very hard to debug (it took me almost 2 days to find it).
So adding a counter to provide external visibility, and if a similar bug
happens in the future, it would be more obvious that this counter
dropped while the actual failure rate remains the same.
=> thriftbp: Add closed connections counter to client pools

README.md, external.bzl, go.mod, go.sum, internal/gen-go/reddit/baseplate/baseplate-consts.go, internal/gen-go/reddit/baseplate/baseplate.go, internal/gen-go/reddit/edgecontext/edgecontext-consts.go, internal/gen-go/reddit/edgecontext/edgecontext.go, retrybp/BUILD.bazel, retrybp/filters.go, retrybp/filters_internal_test.go
Also upgrade thrift to 0.14.0.
=> retrybp: Handle thrift retryable exceptions in RetryableErrorFilter

tracing/tracer.go
This change improves the race condition detected in
https://cloud.drone.io/reddit/baseplate.go/1690/2/2.
To completely fix that we would need to change the globalTracer into an
atomic value, which is actually overkill as this race condition would
almost only happen in tests and is not a real threat to production code.
=> tracing: Improve race condition in tests

tracing/tracer.go, tracing/tracer_test.go
Default to false and remove hyphens from generated uuids, as that could
break zipkin collectors.
=> tracing: Add UUIDIntact config to tracer

.github/workflows/go-ci.yaml, Editor.md, Style.md, WORKSPACE, experiments/experiments.go, httpbp/client_middlewares_test.go, httpbp/errors.go, httpbp/errors_test.go, httpbp/headers_test.go, httpbp/middlewares.go, kafkabp/config_test.go, metricsbp/example_baseplate_hooks_test.go, metricsbp/runtime_stats.go, retrybp/filters_test.go, retrybp/retry_test.go, scripts/linters.sh, thriftbp/client_middlewares.go, thriftbp/client_pool.go, thriftbp/client_pool_test.go, thriftbp/errors.go, thriftbp/server.go, thriftbp/server_middlewares.go, thriftbp/server_middlewares_test.go, thriftbp/thrifttest/mocks.go, thriftbp/ttl_client_test.go, tracing/hooks_test.go, tracing/span.go
And also fix all the things staticcheck complained about.
While I'm here, also upgrade the go version from 1.16.2 to 1.16.5.
=> Enable staticcheck in CI

thriftbp/server_middlewares.go, thriftbp/server_middlewares_test.go
This middleware recovers from panics and reports the error to Sentry.
=> Add thriftbp.RecoverPanic middleware

.github/CODEOWNERS
I'm not going to have the bandwidth going forward to review every PR so I'm taking myself off of the CODEOWNERS.
=> Remove Andrew Boyle from CODEOWNERS

log/wrapper.go, log/wrapper_test.go
=> log: Change default of Wrapper.UnmarshalText to sentry

scripts/bazel_cleanup.sh
To work around https://github.com/bazelbuild/bazel-gazelle/issues/1088.
=> Improve bazel script

thriftbp/thrifttest/server.go
Fixes https://github.com/reddit/baseplate.go/issues/395.
=> thriftbp/thrifttest: Add ServerConfig.EdgeContextImpl

.github/CODEOWNERS
This team is set up for auto-assignment of 2x folks
=> Update CODEOWNERS to the baseplate team

.github/workflows/go-ci.yaml, Editor.md, Style.md, errorsbp/batch_example_test.go, internal/gen-go/staticcheck.conf, metricsbp/log.go, scripts/linters.sh, staticcheck.conf
Staticcheck with all checks is a superset of golint.
=> Enable all checks on staticcheck and remove golint

thriftbp/client_middlewares.go, thriftbp/client_middlewares_test.go, thriftbp/client_pool.go, thriftbp/headers.go, thriftbp/server_middlewares.go, thriftbp/server_middlewares_test.go, tracing/trace.go
Add SetUserAgent client middleware, and handle User-Agent THeader in
InjectServerSpan server middleware.
=> thriftbp: Add support for User-Agent THeader

configbp/BUILD.bazel, thriftbp/thrifttest/BUILD.bazel, thriftbp/thrifttest/server.go, thriftbp/thrifttest/server_example_test.go
Convert the example of thrifttest.NewBaseplateServer to a real, full
file example.
=> thriftbp/thrifttest: Real example for NewBaseplateServer

metricsbp/statsd.go
That was removed during the fix of the double-flush bug.
I tried to write a test for it but can't get it to pass reliably, likely
due to the caching on the system level (data written to an udp
connection is not always readable on the other end of the connection
immediately). No test is better than flaky test.
=> metricsbp: Wait for flushing to finish in Statsd.Close

scripts/linters.sh
Currently the only shell script we have is linters.sh.
=> Fix things shellcheck complained on shell scripts

httpbp/server.go, thriftbp/server_middlewares.go
Add a couple small tweaks to server middleware (both thrift and http).
=> Server middleware tweaks

filewatcher/filewatcher_test.go
When overwriting the file with new content for test, the overwriting was
done incorrectly, via overwriting in place, and can sometimes cause the
filewatcher to be triggered twice (once when opening and truncating the
file, once when the file is closed and writing is done). Add a helper
function to do the writing on a separated file and then use os.Rename
for an atomic move instead.
=> filewatcher: Fix flaky tests

filewatcher/filewatcher_test.go
Follow up on 846e891, the create-write-close writing can also trigger
filewatcher twice and can make the test flaky when the machine running
it is slow (e.g. when the CI is slow). Change all writes in filewatcher
tests to use the helper to do the atomic write and make sure that they
only trigger filewatcher once.
=> filewatcher: Fix flaky tests 2

go.mod
In preparation of cutting v0.9.3 release.
=> Retract v0.9.2

thriftbp/server.go
This PR implements the experimental server configuration `ThriftSocketTimeout` as detailed in internal discussions.
=> add thrift socket timeout impl

thriftbp/server_transport.go
Call Add(1) in Accept as for server TTransport its Open was never
explicitly called.
=> Fix thriftbp.CountedTServerTransport

breakerbp/failure_ratio.go, httpbp/headers_test.go, httpbp/middlewares.go, httpbp/prometheus.go, internal/limitopen/limitopen.go, kafkabp/consumer.go, thriftbp/client_pool.go, thriftbp/prometheus.go, thriftbp/prometheus_test.go, thriftbp/server_middlewares.go, thriftbp/server_transport.go, thriftbp/ttl_client.go
Except the ones in example code, and the one emitted from the
experimental thrift server config.
=> Add prometheus metrics to all the existing statsd metrics

thriftbp/prometheus_test.go
Instead of using a fixed buffer size of 2 for the channel, spawn a
goroutine to drain the channel. This way the unit test is more robust
against future changes to the Collect implementation.
=> thriftbp: Minor unit test improvement on clientPoolGaugeExporter

errorsbp/batch.go
I was obviously way overthinking while writing the original code :$
=> errorsbp: Remove prefixedError

log/wrapper.go
This is the prometheus version of metricsbp.LogWrapper.
=> log: Add PrometheusCounterWrapper

kafkabp/rack.go, log/wrapper.go, log/wrapper_test.go, secrets/config.go
Relax the interface to a minimal Counter and drop the prometheus
dependency.
=> log: PrometheusCounterWrapper -> CounterWrapper

redis/cache/redispipebp/monitored.go
In af1f91b0c661b89078a42cab5ccbe36c2b9e1d44 I totally forgot to add this
label, so when a service has 2 redispipebp.MonitoredSync the prometheus
metrics won't be able to distinguish between them.
=> redispipebp: Add name to prometheus metric labels

thriftbp/prometheus.go
Classic off-by-1 error :P
Also I think the correct term is mebibyte not megabyte, so fixing that
as well.
Closes # 
[Design Doc]()
[Jira]()
=> thriftbp: Fix comment

thriftbp/server_middlewares.go
And also remove it from BaseplateDefaultProcessorMiddlewares.
There are two places in thrift code checks for ErrAbandonRequest. The
most important one is in compiler generated Process function, which
happens before all the middlewares, so doing the "translation" in a
middleware will have no effect there. The other, minor one is in
TSimpleServer to close the client connection directly if it's an
ErrAbandonRequest, but if we didn't return ErrAbandonRequest the Process
function will try to write the error returned to the client and that
will fail, so TSimpleServer will close the connection anyways, and
having this middleware will not really do anything extra differently.
Services should do the context.Canceled -> thrift.ErrAbandonRequest
translation in their endpoint handler code instead.
=> thriftbp: Deprecate AbandonCanceledRequests

prometheusbp/promtest/testutil.go, prometheusbp/promtest/testutil_test.go
Closes # 
[Design Doc]()
promtest: Checkdelta test check improved for float inputs, because rounding could fail anyway good tests
[Jira]()
=> promtest: Checkdelta float compare fix

thriftbp/client_middlewares.go
In client middlewares, any error defined in thrift IDL is actually not
returned via the error return, but written as part of the result
TStruct. As a result, none of the current client middlewares actually
get the exceptions defined in IDL correctly (this includes
baseplate.Error).
Add a helper function to get those errors out of the result TStruct via
reflection.
=> thriftbp: Fix IDL exceptions in client middlewares

events/events.go, events/events_test.go
This is needed to support custom exposure from experiments v2.
=> events: Add PutRaw API

baseplate.go, baseplate_test.go
This helps mitigate against a race condition from kubernetes between
draining the traffic from the pod and sending the pod SIGTERM.
=> baseplate: Add StopDelay to Config

redis/cache/redispipebp/monitored.go, redis/db/redisbp/hooks.go, redis/db/redisbp/hooks_test.go, redis/db/redisbp/monitored_client.go, redis/internal/redisprom/doc.go, redis/internal/redisprom/metrics.go
Closes # 
This adds new Prometheus metrics that are closer to the BP.spec than existing ones.
Unfortunately there are some information that isn't available so I left these labels out.
No idea how to test
=> feat(prom): Add Prom metrics closer to the BP.spec for Redis clients

internal/faults/faults.go
These logs could fire on every request, so rate limiting them will help prevent them from being too chatty in the case where many errors occur within a short timeframe.
This is a direct follow-up to https://github.com/reddit/baseplate.go/pull/675.
=> Rate limit logs.

internalv2compat/compat.go
Closes # 
https://github.com/reddit/baseplate.go/pull/679
Missing exported method for initializing the thrift trace provider. 
[Design Doc]()
[Jira]()
=> export setter for thrift trace provider

breakerbp/failure_ratio.go
A typical use case of circuit breaker would often have this scenario happen:
1. Client pods have circuit breaker set up for server, with same settings
2. Server goes into an outage
3. All client pods' circuit breakers tripped at roughly the same time
4. Server recovered from outage
5. Because all client pods' circuit breakers are tripped, server does not get a lot of request, its HPA is running near minimal
6. All client pods' circuit breakers' timeout happen at roughly the same time, they all start to send requests to the server again at roughly the same time
7. Server's HPA is not able to scale up quickly enough with the sudden influx of traffic, so the load crashes the server pods again
So, adding a jitter to the timeout will help spread the recovering traffic to the server, which …
=> breakerbp: Add jitter to timeout

breakerbp/failure_ratio.go
Follow up on 0671ecd, also report the jittered timeout as a gauge.
=> breakerbp: Add a gauge to report jittered timeout
