thriftpool/bench_test.go
thriftpool/channel.go
thriftpool/channel_test.go
thriftpool/doc.go
thriftpool/errors.go
thriftpool/interface.go
thriftpool/interface_test.go

This package defines an thrift client pool interface, and comes with a
channel based implementation.
The benchmark result shows that the channel based implementation takes
~100ns for a Get/Release pair calls.
$ go test -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: github.com/reddit/baseplate.go/thriftpool
BenchmarkPoolGetRelease/channel-8         	12180511	        95.9 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/reddit/baseplate.go/thriftpool	1.288s

Add thriftpool package

---

secrets/store_test.go

dir created by `ioutil.TempFile` is not watchable by fsnotify (tested in OS X).
Use `ioutil.TempDir` to create a watchable dir prior the tmp file.

use TempDir to create watchable dir prior to tmp file creation

---

secrets/secrets.go
secrets/secrets_test.go
secrets/store_test.go

Migrate SimpleSecret and VersionedSecret from string to Secret.
Also some test improvements:
- Close tmp files after writing to make sure the writes are flushed to
the disk
- Delete the tmp directories after tests
- Reduce the sleep time on TestSecretFileIsUpdated as we flushed the
writes now

secrets: Define Secret type

---

secrets/secrets.go
secrets/store.go
secrets/store_bench_test.go
secrets/store_test.go

Middleware allows caller to add custom functions to work with Secrets as they see fit. This option allows multiple layers callback and also leaves concurrent and blocking problem to the caller.
~We still need to open up Secrets to allow the caller to interact with it.~
This is entirely open for discussion. I just find it easier to express the idea with actual code :)
Middleware chaining benchmark result:
```
go test -bench=. -benchmem * -test.v -run=BenchmarkStoreMiddlewares
goos: darwin
goarch: amd64
BenchmarkStoreMiddlewares/number_of_middlewares_1-12               52531             22815 ns/op             288 B/op          8 allocs/op
BenchmarkStoreMiddlewares/number_of_middlewares_2-12               51770             23652 ns/op             304 B/op          9 allocs/op …
```

Use middleware approach to handle callbacks

---

mqsend/errors.go
mqsend/mqsend_linux.go
mqsend/mqsend_mock.go
mqsend/mqsend_mock_test.go
mqsend/mqsend_test.go

Add two error types for the two common errors that could be returned by
Send: TimedOutError and MessageTooLargeError, so that the callers can
inspect them and handle accordingly.

mqsend: Add error types

---

metricsbp/doc.go
metricsbp/statsd.go
metricsbp/statsd_test.go

go-kit's influxstatsd implementation gives us the ability to use
tags/labels in statsd metrics.
This change changed the underlying type but should be mostly
backward-compatible.

metricsbp: Use influxstatsd instead of statsd implementation

---

runtimebp/cpu.go

With lower NumCPU reported now, the old formula of NumCPU*2-1 no longer
works. This change will help us to test new formulas, before we can
change to the default formula to a better one later.

runtimebp: Allow set GOMAXPROCS with a customized formula

---

runtimebp/cpu.go

I thought runtime.GOMAXPROCS returns the new value set, but apparently I
was wrong and it actually returns the previous value. So make
runtimebp.GOMAXPROCS to return both old value (from the return value of
runtime.GOMAXPROCS) and new value to make it more useful for debugging.
This is a breaking change, but the impact should be minimal.

runtimebp: GOMAXPROCS return two values instead of one

---

metricsbp/baseplate_hooks.go
metricsbp/baseplate_hooks_test.go
metricsbp/example_baseplate_hooks_test.go
tracing/errors.go
tracing/hooks.go
tracing/hooks_test.go
tracing/span.go
tracing/span_test.go
tracing/thrift.go
tracing/tracer.go

This PR adds "Hooks" into the tracing lifecycle like the [Observers](https://github.com/reddit/baseplate.py/blob/master/baseplate/__init__.py#L32-L86) in `baseplate.py`.  This allows us to hook custom functionality into the Baseplate request lifecycle and the Span lifecyle.  
This also includes hooks for Metrics which allow us to automatically add timers around Spans and success/fail metrics.

Span hooks

---

edgecontext/edgecontext.go
edgecontext/token.go
timebp/doc.go
timebp/microsecond.go
timebp/microsecond_test.go
timebp/millisecond.go
timebp/millisecond_test.go
tracing/span.go
tracing/zipkin.go
tracing/zipkin_test.go

Move tracing.ZipkinTimestamp, tracing.ZipkinDuration, and
edgecontext.TimestampMillisecond into that package.
Also a slight behavior change on how timebp.TimestampMicrosecond handles
"null" in json marshal/unmarshal.

Add timebp package

---

edgecontext/init_test.go
edgecontext/validator.go

Also disable logging in tests as the failure auth tests will call
log.Errorw.

edgecontext: Also verify the signing method

---

tracing/span.go
tracing/zipkin.go

Add Baseplate.py 1.2 server timeout span annotation. Note that this
change does not add the metrics.

tracing: Add server timeout span annotation

---

log/wrapper.go

There's no reason we should force user of this package to import
"go.uber.org/zap/zapcore" just in order to call ZapWrapper.

log: Change ZapWrapper arg from zapcore.Level to Level

---

metricsbp/baseplate_hooks.go
metricsbp/baseplate_hooks_test.go
metricsbp/example_baseplate_hooks_test.go
tracing/error_reporter_hooks.go
tracing/hooks.go
tracing/hooks_test.go
tracing/span.go

* Remove 'Prefix' from metricsbp.BaseplateHook
- This should be set by the metrics client and/or whatever backend
is collecting your metrics
* Add 'OnSetTag' and 'OnAddCounter' functions to the `tracing.SpanHook`
interface.
- This brings us close to par with the span Observers in baseplate.py

Span enhancements and cleanup

---

metricsbp/baseplate_hooks_test.go
metricsbp/example_nil_check_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go
metricsbp/sys_stats.go

Simplify it that canceling the passed in context is sufficient to
reclaim all the resources and stop all the goroutines.
The old code also has a bug that if NewStatsd is called with empty
Address, calling RunSysStats could panic. It's fixed with this change as
well.
* Actually it's "delete", so this is a breaking change.

metricsbp: Deprecate* Statsd.StopReporting

---

runtimebp/doc.go
runtimebp/ip.go
tracing/span_test.go
tracing/tracer.go
tracing/tracer_test.go

Export the function as it will be useful for microservices wanted to add
that as a label to their metrics.
I chose runtimebp package over metricsbp package as the use case is not
limited to metrics, and also moving it into metricsbp will cause cyclic
importing.

tracing.getFirstIPv4 -> runtimebp.GetFirstIPv4

---

metricsbp/example_nil_check_test.go

Missed in the previous commit.

metricsbp: Fix ExampleCheckNilFields to use metricsbp.M

---

metricsbp/example_timer_test.go
signing/doc_test.go

Note that I haven't changed `metricsbp.BaseplateHook` and related code/tests/examples. @pacejackson maybe you can do that with your span refactor.

Migrate more metrics related examples to metricsbp.M

---

metricsbp/baseplate_hooks.go
metricsbp/baseplate_hooks_test.go
metricsbp/example_baseplate_hooks_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go
metricsbp/sys_stats.go

Change NewStatsd to return *Statsd instead of Statsd, and for all
*Statsd functions, fallback to M when it's nil.
The global statsd change should eliminated most of the use cases to pass
a Statsd around. But for the few cases that's still useful, this change
will allow it to be nil (zero value) when not needed.

metricsbp: Allow Statsd to fallback to M

---

metricsbp/baseplate_hooks_test.go
metricsbp/doc.go
metricsbp/example_timer_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go

We used to use go-kit's statsd implementation, which only provided
timing as histogram. We have since switched to influxstatsd
implementation, which actually provided both histogram and timing.
I looked into the code, looks like the only difference between them is
that for histograms it's writing to the wire with "|h" while for timing
it's writing to the wire with "|ms".

metricsbp: Split histogram into histogram and timing

---

batcherror/batch.go
batcherror/batch_test.go
batcherror/doc_test.go

Implement Is and As for BatchError so that any error inside the batch
can be inspected with errors.Is and errors.As, including wrapped ones.
Also remove Unwrap, as it's no longer useful.

batcherror: Better inspectibility with Is and As

---

metricsbp/statsd_test.go
metricsbp/sys_stats.go

Since RunSysStats sets gauge value on a per-machine basis, allowing
additional labels would make more sense, otherwise the gauge will just
keeps getting overwritten between the machines.

metricsbp: Add labels to RunSysStats

---

edgecontext/edgecontext.go
edgecontext/init_test.go
edgecontext/validator.go
httpbp/trust_handlers_test.go
secrets/secrets.go
secrets/store.go
secrets/store_bench_test.go
secrets/store_internal_test.go
secrets/store_test.go

Also:
1. Remove the type check after filewatcher.Get, which would never fail.
2. Add Store.Stop()

secrets: Allow adding additional middlewares

---

metricsbp/baseplate_hooks_test.go
metricsbp/example_nil_check_test.go
metricsbp/sample_rate_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go

In influxstatsd implementation, all histograms are not aggregated, and
forwarded to statsd as-is, while counters are aggregated (gauges are
always snapshotted without the conception of sample rate). This means we
usually need a different (lower) sample rate for histograms (including
timings) to avoid sending too much data to statsd.
Split DefaultSampleRate into DefaultCounterSampleRate and
DefaultHistogramSampleRate to resolve this problem.
Also for user convenience, treat zero value of the sample rate configs
as 1, and <0 as 0.

metricsbp: Split DefaultSampleRate into counter and histogram

---

tracing/middlewares.go
tracing/middlewares_test.go

Use the same `endpoint.Middleware` that we are using to inject server spans into the context to also stop the server span after the endpoint has finished.

Stop HTTP spans after endpoint finishes

---

metricsbp/example_nil_check_test.go
metricsbp/sampled.go
metricsbp/sampled_test.go
metricsbp/statsd.go

go-kit's influxstatsd implementation doesn't actually do sample. It
expects the user to do sampling manually, and report the sample rate to
them. Implement SampledCounter and SampledHistogram to actually do
sampling.
Also rename StatsdConfig.Default*SampleRate to *SampleRate, as the
semantic changed because of this change.

metricsbp: Actually sample counters and histograms

---

.drone.yml

This is less useful now and also makes the test result harder to look
at.
While I'm here, also upgrade to go 1.13.7 in drone config.

Remove -v in go test in drone config

---

integrations/doc.go
redisbp/doc.go
redisbp/example_hooks_test.go
redisbp/example_monitored_client_test.go
redisbp/hooks.go
redisbp/hooks_test.go
redisbp/monitored_client.go

These Factory objects allow you to create new go-redis clients
that are monitored by RedisSpanHooks using the span for the
given context.
This also removes the 'integrations' package in favor of a
'redisbp' package, mostly to improve the readability of the
exported structs and functions.

Add redisbp.MonitoredCmdableFactory

---

tracing/trace.go

Our current system for storing trace data only supports string values for binary annotations so we want to also encode boolean values as lower case strings.

Convert all span tags to strings

---

thriftpool/bench_test.go
thriftpool/doc.go

This is closer to how they are used in real world code.

thriftpool: Change the benchmark test to parallel

---

thriftpool/channel.go
thriftpool/interface_test.go

Previously we only decrease number of active connections when we
successfully returned the client to the pool, which means when there are
errors (usually when Close reported error, or when we try to open
a new client in Release and the opener returned an error), we don't
decrease the number, even though semantically the client is returned to
the pool. That leads to the pool reporting exhausted when even we tried
to return every client we got from the pool.

thriftpool: Fix a bug on active connection counting

---

thriftclient/client.go
thriftclient/client_test.go
thriftclient/doc.go
thriftclient/example_client_test.go
thriftclient/testing.go

This package adds a `MonitoredClient`, which is an implementation of `thrift.TClient` that wraps the `Call` to an internal client in a thrift client span.
This is in it's own package because it has to import from `tracing` which currently imports from `tracingbp`.
It also adds 2 other `thrift.TClient` implementations that can be used to mock out clients and help with unit testing.

Add thriftclient package

---

metricsbp/statsd.go
metricsbp/statsd_test.go
thriftclient/client_pool.go

This is a `map[string]string` typedef that allows you to define StatsD labels in a simple way and provides a function to convert itself to the format that the StatsD client expects.

metricsbp: add MetricsLabels type 

---

edgecontext/validator.go
go.mod
go.sum

This fixes https://github.com/reddit/baseplate.go/issues/73.

edgecontext: Use reddit's fork of jwt-go for key rotation

---

redisbp/example_hooks_test.go
redisbp/example_monitored_client_test.go
redisbp/hooks.go
redisbp/hooks_test.go
thriftclient/example_client_test.go
thriftclient/monitored_tclient.go
thriftclient/monitored_tclient_test.go
tracing/example_middlewares_test.go
tracing/hooks_test.go
tracing/http.go
tracing/http_test.go
tracing/log.go
tracing/middlewares.go
tracing/middlewares_test.go
tracing/span.go
tracing/span_test.go
tracing/thrift.go
tracing/thrift_test.go
tracing/trace.go
tracing/tracer.go
tracing/tracer_test.go

Remove some of the tracing API in favor of opentracing API, in details
(this is not an exhaustive list):
- GlobalTracer is no longer exported, use opentracing.GlobalTracer()
instead.
- No longer provide *WithTracer APIs, always use the global tracer.
- Remove CreateServerSpan* APIs, use opentracing.StartSpan with
SpanTypeServer as a SpanTypeOption instead.
- Remove Tracer.NewTrace API, use opentracing.StartSpan without parent
instead.
- Remove Span.Create*Child API, use opentracing.StartSpan instead.
Added APIs:
- tracing.AsSpan() to convert opentracing.Span into *tracing.Span.
- tracing.TestWrapper() for special case of tracing related testing.
- tracing.CloseTracer() to stop the global tracer from reporting.

tracing: Migrate to opentracing API

---

metricsbp/sys_stats.go

metricsbp: Also migrate RunSysStats to use MetricsLabels type

---

metricsbp/timer.go

We mentioned in the doc of Timer that it's nil-safe, so make sure that
Timer.Start is also nil-safe. :)

metricsbp: Make sure Timer.Start is nil-safe

---

edgecontext/req_context.go
edgecontext/req_context_test.go

This is so we can pass the RequestContext header between HTTP services.

Add method to attach the Request Context header to HTTP headers

---

metricsbp/baseplate_hooks.go
tracing/span.go

In baseplate.py, we use "clients" (instead of "client") for client
spans and the component name for local spans. This makes baseplate.go's
behavior the same.
Also add Span.Component() API to support that.

Fix span hook metrics path

---

clientpool/errors.go
edgecontext/validator.go
experiments/experiments.go
experiments/experiments_test.go
experiments/targeting.go
experiments/variants.go
runtimebp/cpu.go
secrets/secrets.go
tracing/errors.go
tracing/span.go

For all errors returned by the libraries, make sure that we always
prefix them with "package_name: ", or even "package_name.FunctionName:".

Add prefix to error messages

---

experiments/experiments_test.go

When checking expected error message, we should also fail the test when
err is nil.

experiments: Fix tests

---

.bazelrc
.drone.yml
scripts/ci-run-bazel-test.sh

We have --test_output=errors so there's no need to print out test logs
in a shell script.

Better way to run bazel tests in CI

---

metricsbp/BUILD.bazel
metricsbp/baseplate_hooks.go
metricsbp/baseplate_hooks_test.go

This reverts commit ee15a9795136a9ade6ccb025ee9dbfcf9d4054fc.
The lack of atomic metrics writing between success/fail and total
counters caused the current implementation not really useful in real
world scenarios. When using success/total as the success rate in
dashboards, we can often see it to be above 1. Reverting the change to
discourage that usage and still use success/(success+fail) instead. We
might want to revisit this idea in the future when we can make sure that
success/fail + total can be counted atomically.

Revert "metricsbp: Add total counter to span hook"

---

clientpool/BUILD.bazel
clientpool/doc.go
thriftclient/BUILD.bazel
thriftclient/doc_test.go

The example doesn't use anything from clientpool directly so it's more
appropriate to put it under thriftclient package. Also added package doc
to clientpool to state that it's low level and shouldn't be used
directly in most cases.

Move clientpool's package example to thriftclient

---

edgecontext/edgecontext.go
edgecontext/edgecontext_test.go
edgecontext/example_middlewares_test.go
edgecontext/init_test.go
edgecontext/middlewares.go
edgecontext/middlewares_test.go
edgecontext/req_context.go
edgecontext/req_context_test.go
edgecontext/validator.go
edgecontext/validator_test.go

This fixes https://github.com/reddit/baseplate.go/issues/122.
Consider the common use case is initialize an implementation then
immediately pass that into the middleware and never worry about it
again, we no longer provide APIs for singleton usage.

edgecontext: Move away from singleton

---

mqsend/BUILD.bazel
mqsend/errors.go
mqsend/mqsend_linux.go
mqsend/mqsend_linux_test.go
mqsend/mqsend_other_test.go
mqsend/mqsend_test.go

Go 1.14 will make EINTR more likely to happen [1], so add retry logic to
make sure we are handling it correctly.
[1] https://golang.org/doc/go1.14#runtime

mqsend: Retry EINTR error

---

mqsend/mqsend_test.go
randbp/BUILD.bazel
randbp/doc.go
randbp/rand.go
randbp/rand_test.go
randbp/sample.go
randbp/sample_test.go
randbp/seed.go
randbp/source.go
tracing/trace.go
tracing/tracer.go

Instead of relying on side effect to proper seed math/rand, use a global
rander randbp.R. This way it's more obvious to tell in code which are
properly seeded and which are not.

randbp: Use a global rander instead of side effect

---

WORKSPACE
experiments/BUILD.bazel
experiments/experiments.go
experiments/experiments_test.go
external.bzl
go.mod
go.sum

I have removed the unnecessary interface and added experiment logging. Experiment logging as part of bucketing seems deprecating so it is enough to include an `Expose` method that services can make use of if they want. The corresponding Python code can be found [here](https://github.com/reddit/baseplate.py/blob/master/baseplate/lib/experiments/__init__.py#L233-L266).
This resolves #3

Add experiment logging by adding an Expose method

---

metricsbp/BUILD.bazel
metricsbp/labels.go
metricsbp/labels_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go
metricsbp/sys_stats.go
thriftclient/client_pool.go

If the package name was metrics, then golint would warn us that the name
metrics.MetricsLabels is redundant. It didn't warn because we had -bp
suffix in the package name, but the same idea still applies.

metricsbp: Rename MetricsLabels to Labels

---

metricsbp/BUILD.bazel
metricsbp/statsd.go

Provide a flushing API for jobs that don't run indefinitely to make sure
that their metrics are emitted before exit.

metricsbp: Add Statsd.Close API

---

thriftclient/client_pool.go
thriftclient/middlewares.go

This makes service code using customized client pool easier to add all
the middlewares recommended by baseplate.

thriftclient: Define BaseplateDefaultMiddlewares

---

metricsbp/BUILD.bazel
metricsbp/timer_test.go

Add sleep time to 100ms to make it less likely to fail, also mark the
test as flaky in Bazel.

metricsbp: Make the timer test less flaky

---

httpbp/BUILD.bazel
httpbp/example_handler_test.go
httpbp/fixtures_test.go
httpbp/handler.go
httpbp/handler_test.go
httpbp/middlewares.go
httpbp/middlewares_test.go
httpbp/response.go
httpbp/response_test.go

This PR trims down the `httpbp` package to be less framework-y and more just a small shim around `net/http` to handle errors in a simple way and one that lets us report them to spans/etc as well as some helpers to simplify writing HTTP responses.

httpbp: refactor v1

---

experiments/experiments.go
filewatcher/BUILD.bazel
filewatcher/doc_test.go
filewatcher/filewatcher.go
filewatcher/filewatcher_test.go
filewatcher/limit_parser_test.go
secrets/store.go

This is a basic sanity protection to avoid being bombed by bad
configuration or attacks.
This is a breaking change, but it should make future filewatcher changes
less breaking. :)

filewatcher: Add size limit

---

log/wrapper.go
thriftbp/example_server_test.go
thriftbp/server.go

Make it more explicit and obvious that logger is only used by
thrift.TSimpleServer, and should not be set to
log.ErrorWithSentryWrapper.

thriftbp: Change the type of ServerConfig.Logger

---

httpbp/headers.go
httpbp/headers_test.go

Since our current edgecontext header transfer is using base64encoded so we need to keep it consistent to attach to the header with base64 format
👓 @pacejackson @fishy

[httpbp]base64 encoding decoding edgecontext

---

httpbp/headers.go
secrets/secrets.go
signing/doc_test.go
signing/interface.go
signing/v1.go
signing/v1_quick_test.go
signing/v1_test.go
signing/versions.go

* Require that the caller pass in a VersionedSecret for both Sign and Verify operations.
* Add a helper method to SimpleSecret to easily get a VersionedSecret.
* Update baseplate to account for this breaking change.

signing: align interface with baseplate.py

---

experiments/doc.go

This package contains a lot of types and it could be confusing for
users to figure out where to start.

experiments: Add starting point in package doc

---

httpbp/example_server_test.go
httpbp/response.go
httpbp/response_test.go

Adds 2 new functions/methods to make using httpbp.Response a little
nicer:
* NewResponse is a nicer way to make a new response for the typical
case where you are not setting a status code.
* Response.WithCode uses the same builder pattern as we used in the
errors code to add some syntactic sugare to make it nicer to set
a custom status code on your Responses.
Note, this also has a small update where you can also now use a `nil` body with the Raw content writer and it will just use an empty string as the body.

Make httpbp.Response a little nicer to use

---

experiments/experiments.go
experiments/experiments_test.go

The `shuffle_version` in experiment json is actually `int`, instead of `string`.
Saw error when parsing experiments:
```
"err":"json: cannot unmarshal number into Go struct field Experiment.experiment.shuffle_version of type string"
```

Update shuffle_version to int instead of string

---

metricsbp/baseplate_hooks.go
metricsbp/baseplate_hooks_test.go

We only need 2 of fail, success, and total. Before this change we use
fail and success, and eventually I think we would want to use fail and
total instead, but keep success for now for backward compatibility.
The reason success and total won't work is that there's no way to
guarantee that the success and total counter gets reported atomically,
so it would lead to situations that success reported a slightly higher
rate than total, which screws up the rate calculating. Although
theoretically this is also an issue with fail+total (or fail+success),
they are much more tolerable than success+total.

metricsbp: Add total counter to span hooks

---

baseplate.go
httpbp/example_server_test.go
thriftbp/example_server_test.go

This is actually 2 changes around the `Context` within a Baseplate.
1. Use the context passed into `baseplate.Serve` as the base for the one used to control the timeout of stopping a service.  This will allow that step to be cancelled if the top level context is cancelled, which it currently is not.
2. Return the `Context` created in `baseplate.New`.  The intention here is that is the context that a service will use as its top level "Serve" context (and is also set up to be cancelled when the Baseplate is closed for you).

Return context from baseplate.New

---

baseplate.go

You can still use negative numbers to indicate that you should wait indefinitely, but we don't want that to be the "default".

baseplate: default StopTimeout to 30 seconds

---

clientpool/interface.go
thriftbp/client_pool.go
thriftbp/client_pool_test.go
thriftbp/doc_client_test.go
thriftbp/example_client_test.go
thriftbp/testing.go
thriftbp/ttl_client.go
thriftbp/ttl_client_test.go

The big change in this PR is updating `thriftbp.ClientPool` to implement `TClient`.  It pulls a client from it's pool to make the actual `Call` and releases is after the call finishes.  This allows you to pass a `ClientPool` in to a thrift client as the `TClient` and avoid the boilerplate of getting a client from a pool and releasing it before each call.
This PR also allows us to trim down the exported interface in `thriftbp`.
1. Don't export `ttlClient`.
2. Update `ttlClient` to allow you to keep a client in a pool indefinetly and configure it using the `ClientPoolConfig`.
3. Remove all the Factory methods that were used to create a ClientPool.
4. Don't export `getClient` or `releaseClient`.

Implement TClient with ClientPool

---

httpbp/BUILD.bazel
httpbp/example_server_test.go
redisbp/BUILD.bazel
redisbp/config.go
redisbp/config_test.go
redisbp/example_config_test.go

This allows us to parse redis client configurations from a YAML file and get the `Options`/`ClusterOptions` objects that you use to create the actual redis clients.

redisbp: add config.go

---

log/BUILD.bazel
log/context.go
log/doc.go
log/log.go
log/log_test.go
tracing/span.go

This is a breaking change, both on how service code should be using the
logger, and on Span.InjectSentryHub has been renamed into
Span.InjectTraceContext.

log: Allow attaching trace id into loggers

---

external.bzl
go.mod
go.sum
thriftbp/client_pool.go

When releasing the client back to the pool, check the error returned by
Call, and close the client to avoid reusing if the error is caused by
network error.

thriftbp: Avoid reusing bad client in ClientPool.Call

---

redisbp/hooks.go
redisbp/hooks_test.go

Baseplate adds a pipeline hook to batch Redis pipeline errors.
The problem is that Redis returns `redis.Nil` error in some cases, e.g. key absence.
These errors should be ignored.
Also, the fix doesn't return errors from the hook in order not to change the default go-redis client error.

Ignore redis nil errors

---

metricsbp/baseplate_hooks_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go

This was removed in 173f703, but it's still useful for writing unit
tests.

metricsbp: Add Statsd.WriteTo

---

baseplate.go
thriftbp/server.go
thriftbp/thrifttest/BUILD.bazel
thriftbp/thrifttest/server.go
thriftbp/thrifttest/server_test.go

This is inspired by httptest.NewServer and allows you to create a new Thrift server listening using the local loopback interface as well as a ClientPool for creating a client to talk to that server.
This can be used to test your thrift service in automated testing.
It _can_ also be used to create fake services for testing your integration, although you might also be served by using the Mocks available in 'thrifttest' for that.

thrifttest: add 'NewBaseplateServer'

---

thriftbp/client_pool.go

This is mainly so we apply middleware before getting a client from the pool, this lets us do things like use a new client if we trigger a retry due to a bad client in middleware.  It also has the side effect of only calling Wrap once rather than every time a new Client object is built.

thriftbp: wrap the ClientPool Call method

---

thriftbp/client_middlewares.go
thriftbp/client_pool.go

Put the default middleware at the end of the client middlewares.  We want these to happen just before the call, that way if we do things like retry requests using middleware, things like spans are triggered twice.

thriftbp: reorder default client middleware

---

thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/client_pool.go
thriftbp/example_client_test.go

Right now we are not including this so the metrics just look like `client.${method}` when they should be `client.${service}.${method}`

thriftbp: include the client service name in the span name

---

edgecontext/edgecontext_test.go
edgecontext/user.go

We should return LoID in this order (fallback to the next one if it's
empty):
1. The logged in user id from the JWT token
2. The loid from the thrift payload
3. The loid from the JWT token

edgecontext: Fix how we return LoID

---

log/log.go

When it's 2, for some logs zap will be unable to get the caller, for
example the log emitted from edgecontext's jwt validator, and cause zap
itself to emit this log:
2020-05-22 02:10:42.683894299 +0000 UTC Logger.check error: failed to get caller

log: Change caller skip level from 2 to 1

---

metricsbp/BUILD.bazel
metricsbp/baseplate_hooks.go
metricsbp/baseplate_hooks_test.go
metricsbp/config.go
metricsbp/timer.go
tracing/span.go
tracing/span_test.go

This PR adds support for the `FinishTime` option to override the stop time of a span.
Along with this, we also export these times as functions and use those when they are set in the metricsbp span hook.
There are 2 reasons for doing this:
1. Not silently ignoring valid options to the `opentracing` functions used to start/stop spans.
2. Some libraries (such as [gocql](https://github.com/gocql/gocql)) support "observing" work by triggering a call _after_ the work is done and reports the start and finish times rather than having hooks before and after the work is done.

Metrics hook stop options

---

edgecontext/req_context.go
edgecontext/validator.go
filewatcher/filewatcher.go
log/BUILD.bazel
log/wrapper.go
log/wrapper_test.go
tracing/span.go
tracing/tracer.go

This technically is a breaking change as we removed log.FallbackWrapper,
but that function is only supposed to be used by code in this repo so it
should be fine. I can also just leave log.FallbackWrapper and mark it as
deprecated, but I fell that's kinda overkill.

log: Better way to fallback Wrapper

---

secrets/testing.go
secrets/testing_test.go

If you use the same underlying raw map to initialize test secrets in parallel, it will trigger race condition checks.  To avoid this, clone the map

secrets: clone the map passed into NewTestSecrets

---

external.bzl
go.mod
go.sum

This gives us the version with socket connectivity check, which would
improve thrift client pool performance.

Upgrade thrift to v0.13.1-0.20200609200738-cfbb905034c9

---

httpbp/fixtures_test.go
httpbp/headers.go
httpbp/middlewares.go
httpbp/middlewares_test.go
httpbp/server.go
httpbp/server_test.go

We forgot to do base64 decoding when handling the edge request header.

Fix httpbp.InjectEdgeRequestContext middleware

---

httpbp/headers.go
httpbp/middlewares.go

This streamlines the encoding/decoding of edge context header so that
devs no longer need to think "is it standard base64 or url safe
base64?", also avoids the need of creating the header struct in
middleware while it's not really needed.
It's unexported as it's really just an internal thing. As a result, in
fixtures_test we still do base64 encoding directly as that's an external
test.

httpbp: Add [en|de]codeEdgeContextHeader

---

metricsbp/sys_stats.go

When we do aggregation for runtime.*.*.something gauges, we actually
convert the hostname and pid part into tags before doing the real
aggregation. We were doing that because we don't have tags in
Baseplate.py.
Since we already have tags in Baseplate.go, we really should just skip
that step.

metricsbp: Switch back to use tags for sys stats

---

thriftbp/server_middlewares.go

Currently it's wrongly rendered as code block because of the extra
space [1].
[1] https://pkg.go.dev/github.com/reddit/baseplate.go/thriftbp@v0.3.1?tab=doc#BaseplateDefaultProcessorMiddlewares

thriftbp: Minor doc comment fix

---

thriftbp/client_pool.go

This was missed on the Suppressor change.

thriftbp: Add Suppressor to ClientPoolConfig

---

experiments/experiments_test.go

Currently running tests for experiments with race detector on will take
close to 30s, which occasionally will cause the bazel tests to timeout
(as the timeout for small tests is 30s).
Change the number of users in TestCalculateBucketWithSeed and
TestCalculateBucket to a quarter what they are now, which reduces the
test running time to <10s.
As we have fewer users per bucket, the derivation of the number of users
per bucket is higher than before, so change the error margin from 0.1 to
0.15.
Also a few small improvements in those two tests to make them slightly
faster.

experiments: Speed up tests

---

metricsbp/baseplate_hooks.go
metricsbp/baseplate_hooks_test.go
thriftbp/client_pool.go

We deprecated some metrics, but kept them for easier transition. This
change actually removes them.
This change will be merged right before the v0.5.0 release.

Remove deprecated metrics

---

experiments/experiments.go

The existing error string construction results in a recursive invocation to itself. This fixes it.

Fix infinite recursion in unknown experiment error

---

thriftbp/BUILD.bazel
thriftbp/client_middlewares.go
thriftbp/client_pool.go

This the only way we can apply the breaker middleware before retry
middleware while using BaseplateDefaultClientMiddlewares. Without doing
it the breaker middleware can only be added as additional middlewares,
and all additional middlewares are after all the default middlewares.

thriftb: Add breaker to BaseplateDefaultClientMiddlewares

---

retrybp/filters.go
retrybp/filters_test.go

context.DeadlineExceeded can be converted to net.Error [1], so we need
to either make sure people always use ContextErrorFilter before
NetworkErrorFilter, which is not ideal, or this.
[1]: https://play.golang.org/p/wGfQvUejHQ7

retrybp: Exclude context.DeadlineExceeded from NetworkErrorFilter

---

log/wrapper.go

CaptureMessage does not come with stack trace while CaptureException
does, and stack traces are useful.

log: Use CaptureException in LogWithSentryWrapper

---

breakerbp/failure_ratio.go
edgecontext/edgecontext.go
edgecontext/req_context.go
edgecontext/validator.go
filewatcher/filewatcher.go
filewatcher/filewatcher_test.go
httpbp/middlewares.go
log/BUILD.bazel
log/wrapper.go
log/wrapper_test.go
thriftbp/client_pool.go
thriftbp/client_pool_test.go
thriftbp/server.go
tracing/hooks.go
tracing/log.go
tracing/span.go
tracing/tracer.go
tracing/tracer_test.go

This allows zap wrapper implementations to take advantage and don't lose
trace id when using Wrapper API to do logging.
This is a breaking change, but since log.Wrapper API is only supposed to
be used internally, for most users the breaking part is only that it can
no longer directly cast into thrift.Logger.

log: Add ctx to Wrapper API

---

WORKSPACE
breakerbp/BUILD.bazel

Upgrade rules_go to v0.23.6, which fixed
https://github.com/bazelbuild/rules_go/issues/1877 that's affecting us.
Also add 'size = "small"' to breakerbp's test target.

Bazel updates

---

external.bzl
go.mod
go.sum

This gives us better connectivity check:
https://github.com/apache/thrift/commit/b93fafd327f6de0f4c7496da5dfd5e8c5d8fe499

Upgrade Thrift (again)

---

batchcloser/closers.go
errorsbp/BUILD.bazel
errorsbp/batch.go
errorsbp/batch_example_test.go
errorsbp/batch_test.go

Also deprecate batchcloser.CloseError, and change
batchcloser.BatchCloser to use AddPrefix instead of CloseError.

errorsbp: Add Batch.AddPrefix

---

log/BUILD.bazel
log/log.go
log/sentry.go
log/sentry_test.go

Also move ErrorWithSentry from log.go to sentry.go.

log: Send extra key values to sentry in ErrorWithSentry

---

randbp/BUILD.bazel
randbp/string.go
randbp/string_example_test.go
tracing/span_test.go

Currently GenerateRandomString could generate empty strings. In some
cases we want to avoid empty strings, so add min length arg to control
that.
Also convert its args into a struct. As a result this is a breaking
change.

randbp: Add min length arg to GenerateRandomString

---

retrybp/BUILD.bazel
retrybp/delay.go
retrybp/delay_test.go
retrybp/retry.go

Although by default upstream retry package already use exponential
backoff with ability to cap max delay, the capping only happens after
the exponential backoff value is calculated. When n (number of retries)
is large enough the calculation of the delay could overflow and go back
to 0, resulting in incorrect delay values.
CappedExponentialBackoff supports the extra capping of n used in the
calculation, making sure that the result delay never overflows.
Also adding FixedDelay to avoid confusion.

retrybp: Add CappedExponentialBackoff option

---

retrybp/delay.go
retrybp/delay_test.go

Based on the user feedback, the name "MaxN" would confuse user to think
that it works as "max attempts". Rename it to MaxExponent to avoid this
confusion.

retrybp: Rename MaxN to MaxExponent

---

baseplate.go
baseplate_test.go
httpbp/example_server_test.go
thriftbp/example_server_test.go
thriftbp/thrifttest/server.go

Add an argument struct to Serve(), allowing for optional slices of `io.Closers` that can shut down gracefully before and after the server.
-----
This is a precursor for adding queue consumers, so that they can be cleanly shutdown alongside the server.

Add struct arg with optional pre- and postShutdown closers to Serve()

---

log/context.go

Some log ingesters have trouble with uint64 that's larger than max
signed int64. Log them as string to avoid troubles.

log: Log trace_id as string instead of int

---

metricsbp/timer.go
metricsbp/timer_test.go

This makes it possible to write something like:
metricsbp.NewTimer(...).OverrideStartTime(start).ObserveDuration()

metricsbp: Make Timer functions return self for chaining

---

batchcloser/closers.go
experiments/experiments.go
httpbp/response.go
runtimebp/cpu.go
secrets/errors.go
secrets/secrets.go

A common cause of error is empty strings, but using %s to construct the
error message will make those cases more confusing. Use %q instead for
most cases.

Cleanup %s usage in error messages

---

filewatcher/filewatcher.go
secrets/errors.go
secrets/secrets.go

I ran into this issue myself or have seen other run into it. Adding a path to the file watcher error message and disallowing empty paths to begin with could help give more directions when setting these things up or debugging them.

Add path to file watcher error & disallow empty paths

---

external.bzl
go.mod
go.sum

The upstream release included my fix to avoid overflow. We would still
prefer our users to use retrybp.CappedExponentialBackoff instead, but
just in case anyone is using the capped policy from upstream directly,
they won't overflow :)

Upgrade retry package

---

clientpool/channel.go

When failed to create initialConnections, add number info to the error
message. Usually it's quite different between the first client failing
and client #15/30 failing so this gives us that information.

clientpool: More detailed error message from init errors

---

log/context.go

This allows users to reuse log.Attach to attach any additional key-value
pairs to be share by all logs using the same context object.

log: Add AdditionalPairs to AttachArgs

---

log/kit_wrapper.go
metricsbp/BUILD.bazel
metricsbp/buffered_writer.go
metricsbp/statsd.go

When using telegraf as the statsd collector, telegraf has a limit of how
many UDP messages can be buffered, and the default go-kit influxstatsd
implementation sends one UDP message per metric on the report interval,
so when we have a lot of metrics, telegraf could be dropping those UDP
messages, thus dropping metrics.
Add a configurable buffer size can help reduce the number of UDP
messages.
Eventually we probably want to upstream this to go-kit.

metricsbp: Buffer udp messages together

---

runtimebp/cpu.go

Our production experience shows that changing GOMAXPROCS from
Ceil(2*NumCPU - 1) to Ceil(NumCPU) reduced context switching and has a
positive impact on latency.
NumCPU is the default GOMAXPROCS from go anyways (but the go default
GOMAXPROCS does not use container-aware NumCPU).

runtimebp: Change default GOMAXPROCS formula to Ceil(NumCPU)

---

thriftbp/client_pool.go
thriftbp/client_pool_test.go
thriftbp/errors.go

It's often useful to have a way to check configuration files for completeness. I usually create a validate command that will check the files for correctness. I believe it makes sense to have configurations themselves provide a validate method too which at the minimum check for required values or returns an error if a value is out of range. This way the validation chain can be partially delegated.

Add a validate method to thriftbp.ClientPoolConfig

---

filewatcher/filewatcher.go

The current code could cause panic when os.Open returned error, as f
would be nil.
While I'm here, also make the log messages slightly more descriptive.

filewatcher: Short circuit when os.Open returned error

---

runtimebp/config.go

This replaces the `fmt.Println` call in `runtimebp/config.go` with printing to stderr like we do in `runtimebp/cpu.go`.
In certain scenarios there is a need to have log messages by baseplate.go filtered out. Since the only occasions where it prints without logger is in runtimebp, they should both print to stderr, allowing it to be filter, i.e. through the user of `2> /dev/null`
---
I noticed we still have a place where we call `fmt.Println` instead of relying on `log.Wrapper`. This passes the logger in via the configuration.
Should we extend the function to pass in `context.Context`? I relied on the comment:
```
// Not all Wrapper implementations take advantage of context object passed in,
// but the caller should always pass it into Wrapper if they already have one,
// or just use …
```

runtimebp: print to stderr instead of stdout

---

kafkabp/config.go
kafkabp/config_test.go

We didn't do that before and that's a bug. Also add an unit test for it.
While I'm here, also allow logger of kafkabp config to be set from yaml,
as we added the support to that in 58d8ccc.

kafkabp: Actually set ClientID in sarama config

---

timebp/microsecond.go
timebp/millisecond.go
timebp/second_f.go

Those comments only apply when we use nanoseconds since EPOCH as
timestamp, not milliseconds/microseconds. I can't remember why I added
them in the first place...
https://play.golang.org/p/u-9jx4H7qZU

timebp: Cleanup incorrect comments

---

log/BUILD.bazel
log/core_wrapper.go
log/core_wrapper_test.go
log/log.go
log/log_test.go

This allows us to mitigate the loss of precision issue without the merge
of [1] to upstream.
In the future if [1] is accepted by upstream, we would still want to
revert this change and use that one instead, as this change makes
logging slightly slower:
$ go test -bench . -benchmem
ts=2020-12-07T23:09:17.386513Z  level=DEBUG     This is a log   {"int": "123", "int64": "1234", "uint64": "1234"}
goos: linux
goarch: amd64
pkg: github.com/reddit/baseplate.go/log
BenchmarkWrappedCore/origin-12           1550918               858 ns/op             384 B/op          1 allocs/op
BenchmarkWrappedCore/wrapped-12          1000000              1054 ns/op             412 B/op          5 allocs/op
PASS
ok      github.com/reddit/baseplate.go/log      4.338s
[1]: https://github.com/uber-go/zap/pull/885

log: Wrap zapcore.Core to convert int64 fields to strings

---

randbp/BUILD.bazel
randbp/seed.go
randbp/seed_test.go

When reading int64 from crypto/rand failed:
1. Log the error to stderr
2. In case of partial failures (read some bytes but not enough for
int64), xor the bytes read against time so that time is not the only
entropy of the fallback seed.

randbp: Small tweak on the GetSeed implementation

---

thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/headers.go
thriftbp/headers_test.go

We only set the header in ctx, but not add it to write header list, and
that's a bug causing we don't really add the header to the wire.

thriftbp: Add header to write header list in SetDeadlineBudget

---

.drone.yml
README.md
WORKSPACE
external.bzl
go.mod
go.sum
internal/gen-go/reddit/baseplate/baseplate.go
thriftbp/client_pool.go
thriftbp/errors.go
thriftbp/server_middlewares.go
thriftbp/server_middlewares_test.go

1. Switch to use TConfiguration to config timeouts and THeaderProtocolID
in client pools.
2. Use the new TException interface to implement IDLExceptionSuppressor.
This is a breaking change with thrift compiler upgrade.

thriftbp: Upgrade thrift

---

log/log.go

Use zap.WrapCore as a standard option instead of doing the manual core
wrapping to apply our wrapper for int to string conversion. This fixes a
bug introduced in c006ae3163 that we accidentally broke caller in logs.

log: Fix missing caller

---

log/log.go
thriftbp/server_middlewares.go

Cherry pick https://github.com/reddit/baseplate.go/pull/326 & https://github.com/reddit/baseplate.go/pull/327 into `0.7.x` branch (which was created on top of `v0.7.2` tag) to prepare for `v0.7.3` release.

Cherry picks for 0.7.x

---

external.bzl
go.mod
go.sum
retrybp/delay.go
retrybp/delay_test.go

There's a breaking change in the upstream, this change makes retrybp
compatible with the new breaking change (and incompatible with the old
one), so that our users can upgrade to the latest version of retry-go.

retrybp: Upgrade retry-go to v3.0.0

---

httpbp/BUILD.bazel
httpbp/errors.go
httpbp/errors_example_test.go
httpbp/errors_test.go
retrybp/delay.go
retrybp/delay_test.go

Define retrybp.RetryAfterError interface and add support to it to
CappedExponentialBackoff, and implement it in httpbp as
httpbp.ClientError.

retrybp: Implement retry-after logic in CappedExponentialBackoff

---

clientpool/BUILD.bazel
clientpool/errors.go
clientpool/errors_test.go
httpbp/errors.go
httpbp/errors_test.go
retrybp/filters.go
retrybp/filters_test.go
thriftbp/client_middlewares.go
thriftbp/errors.go
thriftbp/errors_test.go

Define RetryableError interface, and make RetryableErrorFilter as a
Filter implementation to check against it. Also add Unrecoverable helper
function to be used in favor over retry.Unrecoverable to have better
error wrapping.
Also make clientpool.ErrExhausted and httpbp.ClientError to implement
RetryableError.
As a result, deprecate PoolExhaustedFilter and UnrecoverableErrorFilter.

retrybp: Add RetryableError and RetryableErrorFilter

---

events/events.go
tracing/tracer.go

When the publishing sidecar is having trouble keeping up and messages
piling up in the mq, the memory used by the mq could be count towards
the memory used by the service, and in some cases could cause the
service getting OOM killed.
Make them configurable so for services that would have low memory
request/limit could limit the max memory used by the message queue.
See also: https://github.com/reddit/baseplate.py/pull/553.

events&tracing: Make max mq size configurable

---

log/context.go
thriftbp/server_middlewares_test.go
thriftbp/tracing.go
thriftbp/tracing_test.go
tracing/BUILD.bazel
tracing/span.go
tracing/span_test.go
tracing/trace.go
tracing/tracer.go
tracing/tracer_test.go
tracing/zipkin.go
tracing/zipkin_test.go

Add support to UUID and option UseUUID to Tracer's Config.
Also change the log key for trace id from trace_id to traceID.

tracing: Support UUID

---

metricsbp/sampled_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go
thriftbp/server_middlewares.go

This gives us more accurate metrics when the code reporting metrics is
already sampled outside of the metrics report sampling.
This is a breaking change to convert -WithRate functions inside
metricsbp to take RateArgs struct as the args.

metricsbp: Add AlreadySampledAt support to sampled metrics

---

ecinterface/BUILD.bazel
ecinterface/global.go
edgecontext/edgecontext.go
httpbp/middlewares.go
thriftbp/client_middlewares.go
thriftbp/client_pool.go
thriftbp/errors.go
thriftbp/headers.go
thriftbp/server_middlewares.go

And change all other packages taking ecinterface.Interface as an arg to
fallback to the global one when the arg is nil.

ecinterface: Add global implementation

---

.gitignore
Makefile
cmd/healthcheck/BUILD.bazel
cmd/healthcheck/dummy_test.go
cmd/healthcheck/main.go
cmd/lib/healthcheck/BUILD.bazel
cmd/lib/healthcheck/doc.go
cmd/lib/healthcheck/healthcheck.go
cmd/lib/healthcheck/healthcheck_test.go
cmd/lib/healthcheck/oneof.go

This allows go services to get healthcheck without depending on
Baseplate.py. They can either build the healthcheck binary from
github.com/reddit/baseplate.go/cmd/healthcheck, or create a main package
in their repo and use the library version.
The implementation matches the behavior (including command line flags)
of the Baseplate.py implementation [1], with the exception of unix
domain socket, and added --timeout flag.
Also change the default timeout from Baseplate.py's 30s to 1s, as 30s
for a healthcheck timeout is too high.
[1]: https://github.com/reddit/baseplate.py/blob/develop/baseplate/server/healthcheck.py

Add healthcheck binary and library

---

timebp/microsecond.go
timebp/millisecond.go
timebp/second_f.go

Sometimes we have the need to use for example milliseconds since EPOCH
format in non-json encoding/decoding, so implement
TextMarshaler/TextUnmarshaler, which is supported by most go encoding
libraries.
Make the MarshalJSON/UnmarshalJSON functions just call the new
MarshalText/UnmarshalText functions, but keep the special "null"
handling as those are unique to JSON.

timebp: Make the types also implement encoding.TextMarshaler

---

cmd/lib/healthcheck/BUILD.bazel
cmd/lib/healthcheck/healthcheck.go
cmd/lib/healthcheck/healthcheck_test.go

Actually in the Python version the type and endpoint args are only
positional. This is the full --help output:
usage: baseplate-healthcheck [-h] [--probe {readiness,liveness,startup}]
{thrift,wsgi} endpoint
Check health of a baseplate service on localhost.
positional arguments:
{thrift,wsgi}         The protocol of the service to check.
endpoint              The endpoint to find the service on.
optional arguments:
-h, --help            show this help message and exit
--probe {readiness,liveness,startup}
The probe to check.
So support up to 2 positional args, and use them to override
--type/--endpoint flags, and as a result the go version of healthcheck
can really take the same args as the python version (and more).
Also add unexported runArgs which allows to override the output to be
used …

healthcheck: Support positional type+endpoint args

---

baseplate.go
metricsbp/statsd.go

We used to do that because the upstream implementation (go-kit statsd)
does not provide flushing ability in their ticker goroutine. We
reimplemented the ticker goroutine with the buffered writer change, and
added the ability to do one more flush before exiting, but forgot to
remove the extra flushing in Statsd.Close. This actually causes race
condition when Statsd.Close is called, because two goroutines are gonna
do the flushing at the same time, using the same writer.
While I'm here, also fix the potential deadlock issue in HandleShutdown
callback.

metricsbp: Stop calling doWrite in Statsd.Close

---

thriftbp/client_pool.go
thriftbp/example_client_test.go

It could be confusing on whether the client created from ClientPool is
concurrent safe, and that could lead to footguns, so adding some doc to
explicitly call it out.

thriftbp: Add doc regarding the concurrency of ClientPool

---

thriftbp/client_middlewares.go
thriftbp/errors.go
thriftbp/errors_test.go

Thrift compiler generated baseplate.Error (from Error exception in
baseplate.thrift) does not provide meaningful messages when logged, so
implement WrapBaseplateError to wrap it to another error with meaningful
error message, and provide BaseplateErrorWrapper client middleware to
always do that automatically.

thriftbp: Add WrapBaseplateError and BaseplateErrorWrapper

---

tracing/BUILD.bazel
tracing/start_options.go
tracing/start_options_example_test.go

The new requirement from Baseplate spec regarding the span name of
client spans are not well documented, so add some doc to emphasize it.
Also add an example to it.

tracing: Add more doc and example to SpanTypeOption

---

thriftbp/client_pool.go

YAML defaults to unmarshal into struct fields if the YAML key is all lowercase, i.e. a struct with field `ServiceSlug` will only automatically get set through YAML unmarshalling if the YAML key is `serviceSlug`. To support a slightly more readable format this change adds the YAML tags for common fields in the Thrift client pool configuration.

Add YAML tags for Thrift client pool configuration

---

thriftbp/client_pool_test.go

On Mac OS, binding to a non-localhost address will ask the user for approval. Since unit tests are rebuilt each time, this approval is required each time.
After this change, `go test ./...` does not require any approvals on my Mac.

thriftbp: Listen on localhost in unit tests

---

log/log.go

Previously we are using zap's default duration encoder, which is float64
seconds [1], so a duration of 1ms will show in the log as "0.001", that
can be very confusing because no one knows from a glance what's the
unit.
Override it with string encoder so it would be "1ms" instead.
[1]: https://github.com/uber-go/zap/blob/404189cf44aea95b0cd9bddcb0242dd4cf88c510/config.go#L110

log: Switch to StringDurationEncoder as default

---

thriftbp/errors.go

I just realized that in the previous WrapBaseplateError implementation,
we unwrap the error passed in into baseplate error, and only keep the
unwrapped baseplate error, but drops everything originally wrapped
around it.
Store both the original error and unwrapped baseplate error into the
unexported error struct, so that its Unwrap can return the original
error, but Error can use the original baseplate error to construct for
better error message.

thriftbp: Fix WrapBaseplateError

---

log/log.go

This change makes the `globalLogger` write log messages to the console
before the top-level Init methods are called.  This prevents logs from
being silently dropped when e.g. baseplate.New fails.

log: don't drop logs that happen before Init

---

breakerbp/failure_ratio.go

This change allows introduces yaml tags to the fields of the circuit breaker config. Allowing config to be sourced from a common file and removing the need for a code change when making adjustments

Add yaml serialization tags to breaker config

---

BUILD.bazel
drainer.go
drainer_example_test.go
drainer_test.go
kafkabp/BUILD.bazel
kafkabp/consumer.go
kafkabp/consumer_test.go
kafkabp/group_consumer.go

Inspired by the Baseplate.py change[1], add Drainer implementation on
top-level package so services can use it to fail their READINESS checks.
Also change kafkabp.Consumer.IsHealthy function signature to add context
arg, so it implements the newly added baseplate.Healthyer interface. The
context arg is used by neither of them right now, but we might want to
start using them in other implementations in the future so adding the
arg now can avoid a future breaking change.
[1]: https://github.com/reddit/baseplate.py/commit/c4a815d2729c3e232849b1e8079d3fb698f621ef

baseplate: Add Drainer

---

httpbp/errors.go
thriftbp/errors.go
thriftbp/errors_test.go

There's no guarantee that there's no side-effects in 500, 502, 504, and
507 errors. So be more conservative and don't mark them as retryable by
default.
Also tweak httpbp.ClientError.Retryable logic, to return 0 instead of -1
for codes not in the default list. This way users can implement their
own retrybp.Filter to mark certain codes not in the default list
retryable. On thriftbp the list is already customizable and also we
defer to the next filter instead of mark the error non-retryable when
it's not in the list, so this actually brings us feature parity (kinda)
between thriftbp and httpbp.
The current codes in default retryable list for both httpbp and thriftbp
are:
* 425 (too early)
* 429 (too many requests)
* 503 (service unavailable)

httpbp&thriftbp: Tweak default list for retryable codes

---

baseplate.go
baseplate_test.go
httpbp/example_server_test.go
httpbp/server.go
redis/deprecated/redisbp/example_config_test.go
thriftbp/server.go
thriftbp/thrifttest/server.go

Closes https://github.com/reddit/baseplate.go/issues/366.
Always enable strict yaml parsing, and require users to embed
baseplate.Config with yaml tag of `yaml:",inline"` in their custom
config structs.
Also unexport parseConfig.

baseplate: Implement strict yaml parsing

---

events/events.go
events/events_test.go
mqsend/errors.go
mqsend/interface.go
mqsend/mqsend_linux.go
mqsend/mqsend_mock.go
mqsend/mqsend_mock_test.go
mqsend/mqsend_test.go
tracing/tracer.go
tracing/tracer_test.go

Also switch tracing and events default timeout to 0 so that by default
they run in non-blocking mode, which matches the behavior on bp.py.

mqsend: Support non-blocking mode

---

log/wrapper.go

1. Fix the docstring, currently because of the lack of punctuations at
the end godoc treats "As principles, library code should" as a
section header
2. In UnmarshalText, convert the []byte to string at the beginning of
the function to simplify the code followed

log: Minor fixes regarding Wrapper

---

tracing/BUILD.bazel
tracing/config.go
tracing/span_test.go
tracing/trace.go
tracing/tracer.go
tracing/tracer_test.go

The major open source tracing libraries/standards, including Zipkin,
OpenTracing, and OpenTelemetry are all using 128-bit hex id for traces
and 64-bit hex id for spans. So change our uuid trace/span id to hex id.
cc: @spladug @praxist

tracing: UUID -> Hex

---

cmd/lib/healthcheck/healthcheck.go
thriftbp/client_middlewares_test.go
thriftbp/client_pool.go
thriftbp/doc_client_test.go
thriftbp/thrifttest/mocks.go
thriftbp/thrifttest/server_test.go

Fixes https://github.com/reddit/baseplate.go/issues/362.
Currently there's a semi-widespread footgun of services sharing the
concrete thrift client rather than the client pool between goroutines.
As described in #362, this breaking change hopefully can force them to
fix the issue.

thriftbp: Change ClientPool from implementing TClient to return it

---

retrybp/BUILD.bazel
retrybp/doc_test.go

Since the retry feature is scattered between the 2 packages, retrybp and
retry, it can be confusing for engineers trying to use it to figure out
what's the best practice or even how to get started. So provide a
package example we can point engineers to.

retrybp: Add a package example

---

thriftbp/client_pool.go

When a service with multiple thrift client pools having thrift client
pool errors, it's not always obvious which of the client pools failed,
adding cfg.ServiceSlug into the error message would help identify the
one.

thriftbp: Add cfg.ServiceSlug to newClientPool error messages

---

Style.md

Explicitly call out the situation when two consecutive lines are on the
same indentation level but not the same logical level.

Update style guide

---

thriftbp/client_pool.go

This is the same fix as the upstream Thrift fix [1] [2] that will be
included in Thrift 0.15.0. Doing it here because:
1. We don't have to wait for Thrift 0.15.0 release to get the fix.
2. Thrift 0.15.0 release will actually be a breaking change, but with
this this fix we are no longer being affected by the breaking change,
so that users using Baseplate.go 0.9.0 can upgrade to Thrift 0.15.0
once that's released.
We can potentially revert this fix in the future once we upgraded to
Thrift 0.15.0.
[1] https://github.com/apache/thrift/pull/2435
[2] https://issues.apache.org/jira/browse/THRIFT-5453

thriftbp: Fix DNS resolution in client pool

---

baseplate.go
baseplate_test.go
httpbp/example_server_test.go
redis/db/redisbp/BUILD.bazel
redis/db/redisbp/example_config_test.go
thriftbp/example_server_test.go

Remove NewArgs.ConfigPath in favor of two-step New, and change
DecodeConfigYAML into ParseConfigYAML to support two-step New.
Two-step New gives service code a chance to override some of the parsed
config before using them to initialize Baseplate packages. For example
Config.Sentry.BeforeSend cannot be deserialized from yaml so this is the
only chance for service code to set it.

baseplate: Implement two-step New

---

breakerbp/failure_ratio.go

Currently, when a service want to incorporate a breaker into its health
check, they need kind of store the last error they got from the breaker.
Exposing the underlying gobreaker's State will help simplify that use
case.

breaker: Add FailureRatioBreaker.State()

---

httpbp/client_middlewares_test.go
retrybp/BUILD.bazel
retrybp/doc_test.go
retrybp/filters.go
retrybp/retry.go
retrybp/retry_test.go

Add BreakerErrorFilter, and an example on how to use retrybp with
breakerbp.
Also fix an issue that we are not taking advantage of retry.Context
option to end retries as soon as ctx is canceled.

retrybp: Add BreakerErrorFilter

---

iobp/BUILD.bazel
iobp/counting_sink.go
iobp/counting_sink_example_test.go
iobp/counting_sink_test.go
iobp/doc.go
thriftbp/BUILD.bazel
thriftbp/server_middlewares.go

I've seen devs using bytes.Buffer when they need to get the size of a
serialized object, and usually the unpooled version, which is very
inefficient. So I think it warrants the need to provide CountingSink
from baseplate.go. Here's the benchmark result:
$ go test -bench CountingSink
goos: linux
goarch: amd64
pkg: github.com/reddit/baseplate.go/iobp
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkCountingSink/size-10/pooled-buffer-12          72058828                16.20 ns/op           48 B/op          1 allocs/op
BenchmarkCountingSink/size-10/unpooled-buffer-12        37453972                32.76 ns/op          160 B/op          3 allocs/op
BenchmarkCountingSink/size-10/CountingSink-12           79914986                15.73 ns/op           56 B/op          2 allocs/op …

Add iobp.CountingSink

---

thriftbp/errors.go
thriftbp/errors_test.go

Although we already added BaseplateErrorWrapper to client pool's default
middlewares, since all extra middlewares will be added after the default
middlewares, if user tries to add some error logging custom middleware,
they would need to add BaseplateErrorWrapper again so they can get the
wrapped error in their error logging middleware, and we end up having
double BaseplateErrorWrapper middleware in the chain.

thriftbp.WrapBaseplateError: Avoid double wrapping

---

baseplate_test.go
events/events.go
filewatcher/filewatcher.go
httpbp/client_middlewares_test.go
httpbp/middlewares_test.go
httpbp/server_test.go
log/sentry.go
metricsbp/baseplate_hooks_internal_test.go
metricsbp/baseplate_hooks_test.go
metricsbp/config.go
metricsbp/example_nil_check_test.go
metricsbp/log_test.go
metricsbp/sampled_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go
redis/cache/redispipebp/init_test.go
redis/db/redisbp/monitored_client_test.go
thriftbp/client_middlewares_test.go
thriftbp/server_middlewares_test.go
thriftbp/tracing_test.go
tracing/config.go
tracing/span_test.go
tracing/tracer.go
tracing/tracer_test.go

This change consolidates `tracing.Config` and `tracing.TracerConfig` into one type with corresponding YAML tags which would allow allow us configure the tracing logger. In addition, this provides YAML tags for any other configuration type.
Closes #364

Consolidate config types and YAML annotations

---

log/sentry.go

exception.Stacktrace could be nil, so range exception.Stacktrace.Frames
could cause panic.

log: Fix sentry BeforeSend panic

---

log/sentry.go
log/sentry_test.go

Doing so can cause sentry to no longer cluster errors with slightly
different error messages as the same error. Change it to opt-in instead.

log: No longer swap sentry error type and message by default

---

thriftbp/ttl_client.go
thriftbp/ttl_client_test.go

In the current implementation ttlClient.expiration could never be nil,
so when user set MaxConnectionAge to a negative value to disable TTL it
doesn't really work as intended.
Also add a test for it.

thriftbp: Fix bug in ttl client

---

external.bzl
go.mod
go.sum
tracing/finish_option.go

A library I imported in my code depends on `opentracing-go@v1.2.0` which results in the v1.1.0 (which baseplate depends on) being overwritten.
The problem is they have changed the error log key in v1.2.0 which is a breaking change since it results in the `Span.FinishWithOptions` function ignoring errors.
Can we update the version to v1.2.0 ([release notes](https://github.com/opentracing/opentracing-go/releases/tag/v1.2.0))?
Or, otherwise, we might want to respect both `error` and `error.object` keys.

Update opentracing-go to v1.2.0

---

internal/limitopen/limitopen.go

The current rendering is quite confusing:
https://pkg.go.dev/github.com/reddit/baseplate.go@v0.9.0-alpha01/internal/limitopen#Open

Fix doc comment of limitopen.Open

---

BUILD.bazel
baseplate.go
baseplate_test.go
configbp/BUILD.bazel
configbp/config.go
configbp/config_test.go
external.bzl
go.mod
go.sum
httpbp/example_server_test.go
randbp/seed_test.go
redis/cache/redispipebp/BUILD.bazel
redis/cache/redispipebp/config_test.go
redis/db/redisbp/BUILD.bazel
redis/db/redisbp/config_test.go
redis/db/redisbp/example_config_test.go
thriftbp/example_server_test.go

This commit introduces a breaking API change:
* baseplate.ParseConfigYAML(file, ptr) -> baseplate.ParseConfigYAML(ptr)
According to the new baseplate spec, the config file location should be
determined based on the environment variable BASEPLATE_CONFIG_PATH
There is also a new piece of functionality:
* YAML configuration files interpolate $ENV and ${ENV} from the environment
This is also a new addition to the baseplate spec.

Update baseplate.go to meet upcoming requirements for environment substitution in configs

---

log/context.go
tracing/span.go
tracing/tracer.go

Creating a contextual sentry hub is not very straight forward, and when
user uses the ctx returned from log.Attach with log.ErrorWithSentry,
they would expect the sentry report also have the info they attached.
Also remove tracing/span.InjectTraceContext, as it's really just a
shorthand for log.Attach and it's not really used anywhere else.

log: Attach attaches both sentry hub and logger

---

thriftbp/client_pool.go

Thanks to YAML strict parsing I noticed that we do not explicitly map the breaker configuration for Thrift pool clients.

Add explicit yaml tag for Thrift circuit breaker

---

httpbp/BUILD.bazel
httpbp/client_middlewares.go
httpbp/client_middlewares_test.go

Fix one bug: when status code >= 500 and closing the body does not error
(it won't error in majority of cases), we do not actually report error
to the circuit breaker.
Also fix a few inefficiencies:
1. When loaded is true, newBreaker is not used, so we can return it back
to the pool immediately, instead of defer'd.
2. Use DrainAndClose instead of ReadAll and Close, as
io.Copy(io.Discard) is more efficient than ReadAll.
3. Use pointer for the breaker in the pool and the map.
Also avoid dealing with interface{} from breaker.Execute, and add a test
to CircuitBreaker.

httpbp: Fix CircuitBreaker

---

log/BUILD.bazel
log/wrapper.go
log/wrapper_test.go
log/zap_wrapper_test.go
thriftbp/server.go

This would help people search for logs from certain upstream
dependencies, for example they can search for "from:thrift" for logs
produced from thrift's TSimpleServer.
This is a breaking change. But the majority of the internal usage are
from yaml config parsing, and there are only 19 direct usages of
log.ZapWrapper from internal code search, and the majority of the 19 are
from my team's monorepo.

log: Add kv support to ZapWrapper

---

thriftbp/client_pool.go
thriftbp/ttl_client.go
thriftbp/ttl_client_test.go

For every ttlClient that has a ttl, add a background goroutine to
refresh the connection when ttl hits.
This adds one goroutine per connection in the pool, until the connection
fails to refresh.
Both IsOpen and Call are protected by a locked state now. When ttlClient
is used, we always call IsOpen first then Call, and in theory these 2
calls might not be using the same connection (e.g. IsOpen is called
right before the connection expires), but even in that scenario, Call
would use a freshly refreshed connection, so things should still work.

thriftbp: Add background refresh for ttlClients

---

baseplate.go
httpbp/server.go
thriftbp/server.go

Deprecate (make them no-op) for now, will remove in next breaking
release (v0.10.0).

Deprecate server timeout from thrift and http servers

---

thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/prometheus.go
thriftbp/prometheus_test.go
thriftbp/server_middlewares.go

This PR adds Prometheus metrics for Thriftbp client based on the [baseplate.spec](https://github.snooguts.net/reddit/baseplate.spec/blob/master/component-apis/prom-metrics.md#thrift).
Background:
All Prometheus metrics changes will be merged in the `prometheus` branch. We are adding this `prometheus` branch because if we cut a point release and the master branch only has partial support for Prometheus metrics it could leave some upgraded repos in a confusing state where they have some metrics and not others. Additionally the prometheus metrics changes are too big for a single PR. So the compromise is to merge all incremental Prometheus metrics into this new branch, then once complete we can merge into the master branch.
The expected work that will need to be merged into this `prometheus` …

Add prometheus metrics for Thrift client

---

errorsbp/batch.go
errorsbp/batch_size_example_test.go
errorsbp/batch_size_test.go
errorsbp/batch_test.go

This is helpful in unit tests to verify that a function returned the
exact number of errors in a batch as expected.
Also add Batch.Len() helper function.

errorsbp: Add BatchSize

---

thriftbp/server.go

`thriftbp.ServerConfig.Logger` is an optional configuration field that is currently always being overwritten. This PR adds a `nil` check to prevent losing the original configuration

prevent overwriting server logger config

---

httpbp/middlewares.go
httpbp/middlewares_test.go

This will check if the returned error is an HTTPError and will
suppress it if it's not a 5xx error or higher.

Suppress non-5xx HTTPErrors in httpbp.InjectServerSpan

---

httpbp/middlewares.go
httpbp/server.go
httpbp/server_test.go

While recovering from panics isn't necessary to avoid the server crashing like it is in thrift, the monitoring from baseplate.go is blind to panics in httpbp. This change adds an unexported middleware that is always applied to http requests that will recover from any panics and bubble those up the call as an HTTPError.

Add panic recovery middleware to httpbp

---

grpcbp/client_middlewares.go
grpcbp/prometheus.go
grpcbp/server_middlewares.go
grpcbp/server_middlewares_test.go

The original PR had to be reverted due to a cherry-picking snafu ([ref](https://github.com/reddit/baseplate.go/pull/447#issuecomment-999110028)), so this is literally a copy and past of the original PR: https://github.com/reddit/baseplate.go/pull/447.
See original PR for description and comments.

Add prom metrics to grpc unary client and server middleware

---

grpcbp/client_middlewares.go
grpcbp/prometheus.go
grpcbp/prometheus_test.go
grpcbp/server_middlewares.go
grpcbp/server_middlewares_test.go
grpcbp/tracing.go
internal/prometheusbp/spectest/spec.go
internal/prometheusbp/spectest/spec_test.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/prometheus.go
thriftbp/prometheus_test.go
thriftbp/server_middlewares.go

There is some confusion around the `*_service` label representing the name of the rpc server when really it should be the fully qualified name of the rpc service. This PR attempts to fix that confusion.  
This PR also removes the thrift service label, re: https://github.snooguts.net/reddit/baseplate.spec/pull/40.
This PR also adds a prometheus metrics spec test for grpc.

Fix "_service" vs "_slug" labels

---

thriftbp/server.go

This reverts commit bc086bdc11206042e0bde3e7ee5bbd3926a5194d.
As mentioned in [1], this override is supposed to happen.
[1]: https://github.com/reddit/baseplate.go/pull/454#discussion_r770998691

Revert "prevent overwriting server logger config (#452)"

---

httpbp/client_middlewares.go
httpbp/middlewares.go
httpbp/prometheus_test.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/server_middlewares.go

While @kylelemons and I were working on making a new [upgrader](https://github.snooguts.net/reddit-go/baseplate-go-updater) for baseplate.go v0.9.2, we realized it would be better to add the Prometheus metric middleware by default so we don't have to add it for each repo. That means we would like to cut another tag v0.9.3 after this change is merged.

Add prometheus middleware to default middleware

---

log/wrapper_example_test.go
metricsbp/baseplate_hooks_internal_test.go
metricsbp/baseplate_hooks_test.go
metricsbp/config.go
metricsbp/log_test.go
metricsbp/sampled_test.go
metricsbp/statsd.go
metricsbp/statsd_test.go

Add BufferInMemoryForTesting to metricsbp.Config, with yaml tag
disabled, to be used by test code that reads from the metricsbp.Statsd
buffer explicitly.

metricsbp: Default to use blackhole sink without Endpoint

---

httpbp/client_middlewares.go
httpbp/errors.go
httpbp/middlewares.go
prometheusbp/promtest/testutil.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/prometheus_test.go
transport/constants.go

For thriftbp, we used to use two MonitorClient middlewares, one before
and one after Retry, to record both raw and -with-retry metrics, so do
the same thing for PrometheusClientMiddleware.
For httpbp, move PrometheusClientMetrics to before Retries so it records
the metrics with retries, same as how MonitorClient middleware is doing
today.

Adjust default client middleware order to handle retries

---

clientpool/channel.go

This seems to be triggered by envoy closing the connections differently
from thrift servers.

Fix connect leak from clientpool

---

redis/cache/redisx/request.go
redis/cache/redisx/request_benchmark_test.go
redis/cache/redisx/syncx.go
redis/cache/redisx/syncx_test.go

Add support for *string data receiver in redisx
Using `*string` receiver for data from redis enables distinguishing between empty string values and `nil` (e.g. stored empty string vs. cache miss).

Add support for *string in redisx

---

httpbp/middlewares.go
httpbp/prometheus.go
httpbp/prometheus_test.go
internal/prometheusbp/spectest/spec.go
internal/prometheusbp/spectest/spec_test.go

This adds a separate label for HTTP Prometheus server metrics to differentiate individual endpoints. For HTTP servers we have the notion of endpoint names, depending on whether we want to move away from defining them as part of a HTTP server router we could also use a different naming schema.

Add http_endpoint label for Prometheus metrics

---

thriftbp/client_middlewares.go
thriftbp/prometheus.go
thriftbp/prometheus_test.go
thriftbp/server_middlewares.go

For thrift's server middleware, the error type is of TException instead
of error, so usually freeform errors need to be wrapped by
thrift.WrapTException, and just try to get the type via %T will hide the
actual type returned by the server handler.
Add a helper function stringifyErrorType to try to unwrap such cases.

thriftbp: Handle wrapped TException in prometheus middlewares

---

httpbp/client_middlewares_test.go

https://github.com/reddit/baseplate.go/runs/5384488436?check_suite_focus=true
This is likely caused by the previous timeout was too short and on some
slow runs it did not have enough time to react.

httpbp: Fix flaky test

---

thriftbp/server_middlewares.go

Right now PrometheusMiddleware is the leaf middleware. This means that its defer function doesn't see panics as being a wrapped error. So it logs them as successes. Making the RecoverPanic middleware the leaf appears to solve this problem

🐛 | Swap Prometheus and recoverPanic middlewares

---

thriftbp/client_middlewares.go
thriftbp/errors.go
thriftbp/prometheus.go
thriftbp/server_middlewares.go

Right now we expect the user to have the same definition of `baseplate.thrift` than we do but nothing enforces it. In the case of the Prometheus middleware this leads to us not recognizing an error as being a Baseplate.Error and therefore not adding the labels for the error code.
This PR introduces a relaxed interface only to be used by the prometheus middleware to ensure that they will identity a Baseplate.Error as such regardless of past or future changes to the `baseplate.thrift` file.

Relax interface for bpError in the Prometheus middlewares

---

detach/detach_async_example_test.go

In the example, we used ordered output, but there's a race condition
that the order of two goroutines are not guaranteed. So change to
unordered output.
Example run:
https://github.com/reddit/baseplate.go/runs/5429490555?check_suite_focus=true

detach: Fix flaky test

---

runtimebp/config.go

Logs like `GOMAXPROCS: 48 4` aren't very clear.  Identifying the configuration values in the default
and updated states is useful to the operator.

runtimebp: Clearly log the `GOMAXPROCS` configuration on startup

---

grpcbp/client_middlewares.go
grpcbp/server_middlewares.go
httpbp/middlewares.go
kafkabp/consumer.go
metricsbp/baseplate_hooks.go
prometheusbp/metrics.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/prometheus_test.go
thriftbp/server_middlewares.go
thriftbp/ttl_client.go

Currently in Baseplate spec, we want different string values for bool
values in statsd vs. prometheus metric tags/labels: In statsd we want
capitalized "True"/"False" while in prometheus we want "true"/"false".
This can be confusing and lead to inconsistency, especially when
services are transitioning from statsd to prometheus metrics.
Provide metricsbp.BoolString and prometheusbp.BoolString in hope to help
reduce the confusion. For devs it should be easier to:
* If I'm using metricsbp to emit a metric, use metricsbp.BoolString
* If I'm using prometheus to emit a metric, use prometheusbp.BoolString

metricsbp|prometheusbp: Add BoolString

---

redis/db/redisbp/monitored_client.go
redis/db/redisbp/prometheus.go
redis/db/redisbp/prometheus_test.go

Add a Prometheus exporter interface implementation to the redisbp
`NewMonitoredClient()`.
Signed-off-by: SuperQ <superq@gmail.com>

Add Prometheus metrics to redisbp

---

redis/db/redisbp/monitored_client.go
redis/db/redisbp/prometheus.go
redis/db/redisbp/prometheus_test.go

1. Move the Desc from the exporter to global variable as they really
don't change between different exporter instances.
2. Add a test to make sure that a service creating multiple redisbp
clients won't cause prometheus exporter registration issues.
cc @SuperQ

redisbp: Minor improvements on the prometheus exporter

---

clientpool/channel.go
clientpool/channel_test.go
thriftbp/client_pool.go
thriftbp/client_pool_test.go

Currently ClientPoolConfig.InitialConnectionsFallback is default to
false, due to how zero values in go work. Deprecate it to make it
default to true, because cascading failures during an outage is in
general much worse.
Add InitialConnectionsNoFallback to allow the current default behavior
(that could cause cascading failures) for services that absolutely need
it.
Also instead of fallback to 0 connections, return whatever connections
we already established with the pool. This requires a small behavior
change inside clientpool package, that clientpool.NewChannelPool now
could return both non-nil Pool and error. An internal code search shows
that there are 2 services using that directly (we probably should have
made that an internal package to avoid that, but that ship has already
sailed). …

thriftbp: Deprecate ClientPoolConfig.InitialConnectionsFallback

---

httpbp/middlewares.go

They are currently inconsistent and rendered weird:
https://pkg.go.dev/github.com/reddit/baseplate.go@v0.9.5/httpbp#DefaultMiddleware

Tab vs. Space fix

---

filewatcher/filewatcher.go
filewatcher/filewatcher_test.go

Currently filewatcher only work on push mode, by using fsnotify to
monitor the parent directory. This might break when the whole parent
directory is remounted. Add pull mode, that checks the file mtime when
Get is called, and force reload the file if the mtime is after the last
parsed mtime.

filewatcher: Change to pull+push mode

---

ecinterface/global.go
filewatcher/doc_test.go
filewatcher/filewatcher.go
internal/limitopen/limitopen.go
kafkabp/consumer.go
kafkabp/rack.go
secrets/config.go

Replace all current explicit log.ErrorWithSentry(-Wrapper) calls with
log.DefaultWrapper plus a prometheus counter.
This way, for services not migrated to prometheus, they still get the
same sentry report today (as log.DefaultWrapper is
ErrorWithSentryWrapper today); But for services migrated to prometheus,
they could override log.DefaultWrapper early in their main [1] to
eliminate unnecessary sentry reporting and monitor on the prometheus
counters instead.
[1]: Example:
log.DefaultWrapper = log.ZapWrapper(log.ZapWrapperArgs{
Level: log.WarnLevel,
KVPairs: map[string]interface{}{
"from": "default-wrapper",
},
})

Eliminate all explicit log.ErrorWithSentry(-Wrapper) calls

---

thriftbp/headers.go
thriftbp/server_middlewares.go

This is a fix to bring baseplate go in sync with baseplate py.

Workaround a bug in envoy

---

log/wrapper.go

The filewatcher test becomes extremely flaky on Github Actions recently,
and without tb.Helper() call the line number is not useful at all.

log: Add tb.Helper() to TestWrapper

---

filewatcher/filewatcher.go

Because go's select gives no guarantee on which case would be picked
when multiple are unblocked, add an additional ctx check to make sure
that we don't fail the tests because we picked the wrong one.

filewatcher: Fix flaky tests

---

httpbp/middlewares.go
kafkabp/consumer.go
thriftbp/client_pool.go
thriftbp/server_middlewares.go
thriftbp/ttl_client.go

For important prometheus error counters with labels, register them
(With the labels but without Inc/Add), so that we are always emitting 0
even if those error counters never fire. This way they can be monitored
correctly (with rate query producing expected results).

Register important prometheus error counters

---

thriftbp/server_middlewares.go
thriftbp/server_middlewares_internal_test.go

Wrap baseplate error in the error reported in the span in
InjectServerSpan (but not change the error returned by the processor),
as we by default also register a span hook that send the span errors to
sentry, and without WrapBaseplateError the error sent to sentry will be
almost unreadable.

thriftbp: Wrap baseplate error in InjectServerSpan

---

thriftbp/prometheus.go

Fix typo in thrift connection housekeeping metric name

---

.github/workflows/go-ci.yaml
go.mod
go.sum
log/log.go
log/version.go
log/version_test.go

Taking advantage of go 1.18's new -buildvcs flag, read the version info
from runtime/debug.BuildInfo when no version is stamped in log package.
Although we don't have -buildvcs in our production builds yet, this
makes us ready to take advantage of that whenever it's ready.
This also requires us to drop support to go 1.17, as
runtime/debug.BuildSetting is added in go 1.18.

log: Add fallback to debug.BuildInfo to version stamping

---

thriftbp/prometheus.go
thriftbp/server_middlewares.go

This can be useful for the service owners to get a sense of what their
clients are setting for the request timeout, and for example if their
SLO is 100ms but a lot of the client requests have a timeout <100ms,
they can talk to the client owners to fix the timeouts.
Note that due to the unusual nature of this histogram, we are usually
looking at the "reverted percentile" of it, for example instead of
looking at 99th percentile, we should be looking at the 1st percentile
for "the 1% of the lowest client set timeouts". As a result this
histogram will not work in a statsd metric, but it should work in a
prometheus metric.

thriftbp: Add prometheus histogram from client set timeout

---

redis/cache/redispipebp/baseplate.go

This PR adds the ability to specify the ReplicaPolicy when creating a clustered Redis client.

Adds ReplicaPolicy Config when creating a clustered redis baseplate client

---

filewatcher/filewatcher.go

With the work of [1], the files watched by filewatcher will soon be no
longer limited to zookeeper nodes, so the previous size limitation
derivated from znode size limit will be hit in the near future.
[1]: https://github.com/reddit/baseplate.py/commit/093fbf4cc1699d244a3d022eeee507b08ce7b18d

filewatcher: Raise default file size limit

---

kafkabp/consumer.go
kafkabp/group_consumer.go
kafkabp/prometheus.go
kafkabp/rack.go

This was missed from the last round of adding prometheus metrics.

kafkabp: Add prometheus timers for consumer and group consumer

---

runtimebp/cpu.go
runtimebp/cpu_test.go

Simplify runtimebp.NumCPU() by removing defer function.
Explicitly return runtime.NumCPU() when `cpu.cfs_quota_us` returns `-1`,
which is usef for no quota. This matches normal Go behavior.
[0]: https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt
Signed-off-by: SuperQ <superq@gmail.com>

Update NumCPU for unlimited quota

---

README.md

It's currently a lie because we forgot to update the mention in README
when updated the compiler.

Update README regarding thrift compiler version

---

runtimebp/config.go

We saw some services confused on what it does, and just set the min
number to some large number and hope that will give them better
concurrency performance.
Since we already don't allow services to customize the formula from yaml
config, it really doesn't make much sense to allow them to customize
min/max from the yaml. Deprecate them and remove them in a future
breaking change.
If a service really need a different GOMAXPROCS from number of
container-aware CPUs, they can call runtime.GOMAXPROCS or
runtimebp.GOMAXPROCS after baseplate.New.

Deprecate runtimebp.numProcesses yaml config

---

thriftbp/thrifttest/server.go
thriftbp/thrifttest/server_test.go

Update thrifttest.Server.Close to close the ClientPool before
trying to close the server. If you don't do this, then the
underlying server.Close will hang while it waits for the client
to close (which won't happen until the server closes) unless
you explicitly set thift.ServerStopTimeout

thrifttest: fix bug where Server.Close hangs

---

runtimebp/cpu.go
runtimebp/cpu_test.go

Apparently cgroup v2 uses different files from v1 for cpu limits, so
the current code does not work in v2 and will always fallback to NumCPU
on the node.

runtimebp: Support cgroup v2

---

internalv2compat/compat.go
log/context.go
log/log.go
log/log_test.go

This PR introduces the hooks necessary for the upcoming v2 compatibility module.
This does not introduce any new user-facing APIs, and it is very clearly indicated that this is not to be used by users.
See BASE-29.

[BASE-29] Create internalv2compat library

---

httpbp/server.go
internalv2compat/compat.go
thriftbp/server.go

For v2 interop, I want to know what protocol the baseplate.Server implements so we can automatically wire up health checks.

Allow detecting HTTP and Thrift implementations of baseplate.Server without using reflection

---

configbp/yaml.go
configbp/yaml_test.go

This is a helper type used in yaml configs, mainly to deal with a helm
bug [1] that large int64 values in yaml config could have precision loss
when going through helm, so we would want to put the string versions of
them in yaml to preserve the precision.
[1]: https://github.com/helm/helm/issues/11045

configbp: Add Int64String type

---

thriftbp/client_middlewares.go

cccd1f1 would cause panic because of typed nil:
panic: value method path/to/baseplate.Error.TExceptionType called using nil *Error pointer
Check reflect value's IsZero instead.

thriftbp: Fix panic caused by typed-nil

---

runtimebp/config.go

This makes overriding GOMAXPROCS easier, and be more consistent with the
expected behavior.

runtimebp: Honor GOMAXPROCS environment variable if set

---

httpbp/admin.go
thriftbp/admin.go

Currently, if the `admin.Serve()` crashes, the resulting error is logged with a warning and the process keeps chugging along without everything it provides (like metrics). Upgrading the log to a Panicw will cause the go routine to panic and crash the program meaning the software can never be in a state where the metics server is not also running successfully.
Test suite ran with `make test`

upgrade log to panic

---

go.mod
go.sum
runtimebp/config.go
runtimebp/cpu.go
runtimebp/internal/maxprocs/maxprocs.go
runtimebp/internal/maxprocs/maxprocs_test.go

Recent baseplate and internal infrastructure changes have led us to revisit our GOMAXPROCS strategy. We will now set GOMAXPROCS (if not specified) based on Kubernetes CPU requests (rather than limits) with a configurable scale multiplier. 
Continuation of https://github.com/reddit/baseplate.go/pull/546.
See: [Design Doc](https://docs.google.com/document/d/10Wd96OT0WpcSStb9GFIoMRM8UTSLtj-xHx439-LgEOg/edit)
I am working on a corresponding Infrared change to plumb through `BASEPLATE_CPU_REQUEST` to all containers and will not merge this until that is deployed.
⚠️ This is a behavior change for services running outside Reddit, and for services running inside Reddit that set their CPU limit != request (we audited this in the design doc).
Unit tests build confidence in the logic; metrics can …

runtimebp: New GOMAXPROCS heuristic

---

internal/prometheusbp/doc.go
internal/prometheusbp/high_watermark.go
internal/prometheusbp/high_watermark_test.go

Benchmark result:
$ go test -bench .
goos: linux
goarch: amd64
pkg: github.com/reddit/baseplate.go/internal/prometheusbp
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkHighWatermarkValue-12          24221392                48.11 ns/op            0 B/op          0 allocs/op
PASS
ok      github.com/reddit/baseplate.go/internal/prometheusbp    1.221s
cc @nanassito

internal/prometheusbp: Add HighWatermarkValue and HighWatermarkGauge

---

ecinterface/global.go
ecinterface/global_test.go

This is primarily necessary during tests, as most production code won't need to change,
but this is based on an internal detail of atomic.Value, which asserts the underlying
type of the value being Store'd is always identical.  Since it doesn't see Interface,
it only sees interface{} (aka any), it actually cares about the concrete type.
There are various ways we can resolve this, covered in the benchmark,
and with the current compiler using atomic.Value with a concrete struct
type seems to be the winner.  This is faster than the older interface version
because the type assertion to a concrete type is faster than the type assertion
to an interface type.

Allow changing the implementation of Interface at run-time

---

baseplate_test.go
filewatcher/filewatcher.go
filewatcher/filewatcher_test.go
go.mod
go.sum
secrets/store_test.go

This replaces the filewatcher part of changes of
https://github.com/reddit/baseplate.go/pull/472.

filewatcher: Implement support for directories

---

breakerbp/failure_ratio.go

In the current implementation, the gauge value is only set when the state of the breaker changes. Which means if a breaker never got tripped, we would not report the gauge value at all.
Set an initial value of 1 in constructor.

breakerbp: Fix prometheus gauge

---

grpcbp/client_middlewares.go
grpcbp/prometheus.go
grpcbp/server_middlewares.go
grpcbp/server_middlewares_test.go
internal/prometheusbpint/spectest/spec.go
internal/prometheusbpint/spectest/spec_test.go

To use v0 and v2 in the same binary, they require identical labels.  The v2 client currently is set up to match the spec, and so update the v0 middleware to do the same for legacy users of this middleware.

Update gRPC metrics to match v2 and spec

---

secrets/secrets.go
secrets/store.go
secrets/store_test.go

Closes # 
Allow baseplate go to read secrets from a vault csi directory
[Jira]()

feat(secrets): support for csi directories

---

httpbp/error_logger.go
httpbp/error_logger_test.go
httpbp/server.go

It's used by upstream server to log some of the kinda-breaking issues,
for example [1]. Since the majority of the http servers at Reddit are
public facing, when those happens it's usually just user messing with
us, not really that the http client we control doing things wrong. This
gives us a way to suppress those logs, and also emit counters to better
track how many times those happened.
This also makes the upstream http server to use the same json logger by
zap as the rest of our code, at warning level.
[1]: https://github.com/golang/go/issues/25192#issuecomment-992276264
~~(I still need to write tests for it, but send it out first to get some early eyes/feedback)~~ done

httpbp: Set http.Server.ErrorLog

---

internal/prometheusbpint/high_watermark.go
redis/internal/redisprom/pools.go
thriftbp/client_pool.go
thriftbp/prometheus.go
thriftbp/prometheus_test.go

Temporarily emit both new and old metrics, we will remove the old metrics after the next release (so the next release will have both).
While I'm here, also:
1. Remove statsd metrics from thrift client pool
2. Change redis client pool metric name following spec change

thriftbp: Match thrift client pool metrics to baseplate spec

---

httpbp/middlewares.go
httpbp/middlewares_test.go
httpbp/response_wrappers.go

Closes # 
`httpbp` middleware, in particular `RecordStatusCode`  and `PrometheusServerMetrics` don't work with chunked HTTP responses because they wrap `http.ResponseWriter` and do not implement `http.Flush`. This updates our response wrapping within in the Middleware to support both the `http.Flush` and `http.Hijacker` interface.
[Design Doc]()
[Jira]()

[fix] `httpbp` middleware doesn't flush chunked responses

---

httpbp/middlewares.go
httpbp/server.go
thriftbp/server_middlewares.go

Because server middlewares are in most call stacks, having "panic" in the function names will cause searching for actual panics in log ingester much harder (you don't want to use "-RecoverPanic" either because they might be part of the actual panic call stack as well).
For thriftbp, since RecoverPanic was exported, keep it as an alias to newly renamed RecoverPanik, but don't use it by default.

thriftbp+httpbp: Rename the RecoverPanic middlewares

---

kafkabp/consumer.go
kafkabp/prometheus.go

Remove statsd metrics, and some tweaks to prometheus metrics to better align with prometheus naming convention (use plural form for units).
For rebalances, since success rebalances happen so rare (consumer rebalances just happen so rare in general, not that we rarely success), the vectored version will cause rate to not really report anything >0, so split that into total and failures_total instead.
For the rack id failures, an internal code search shows that the http one is not used by anything and the aws one is only used by 3 repos, so I opted against keep both and deprecate the old one, and will notify the repo owners instead.

kafkabp: Metrics cleanup

---

thriftbp/client_middlewares_test.go
thriftbp/client_pool.go
thriftbp/prometheus.go
thriftbp/server.go
thriftbp/server_middlewares.go
thriftbp/server_transport.go
thriftbp/thrifttest/server.go
thriftbp/ttl_client.go
thriftbp/ttl_client_test.go

Remove statsd metrics, and rename some prometheus metrics to comply with prometheus naming convention. For renamed prometheus metrics, temporarily emitting both old and new, but mark old ones as deprecated to be removed later.
Also remove some statsd only features:
1. CountedServerTransport is marked as deprecated and no longer used by other code.
2. In ReportPayloadSizeMetrics server middleware, the rate arg is deprecated and the prometheus metrics is always reported.
3. ClientPoolConfig.MetricsTags & ClientPoolConfig.ReportPoolStats are deprecated. The pool stats are always reported as prometheus metrrics.

thriftbp: Metrics cleanup

---

baseplate.go
baseplate_test.go
breakerbp/failure_ratio.go
httpbp/middlewares.go
httpbp/prometheus.go
internal/limitopen/limitopen.go
redis/db/redisbp/example_monitored_client_test.go
redis/db/redisbp/monitored_client.go
retrybp/doc_test.go
signing/doc_test.go

Remove/deprecate statsd metrics, and rename an httpbp prometheus metrics similar to the thriftbp one in
https://github.com/reddit/baseplate.go/pull/581.

Metrics cleanups in other packages

---

runtimebp/internal/maxprocs/maxprocs.go

Since we're not using a real logger here (artifact of previous implementation, I _think_ because logging isn't initialized when this is called – but if that's not the case we can update to use zap) we weren't logging a newline. This was not caught by tests because the maxprocs library doesn't bake in any testing affordances so we had to stub it out.
Before:
```
maxprocs: Updating GOMAXPROCS=8: determined from CPU quotapanic: runtime error: invalid memory address or nil pointer dereference
```
After:
```
maxprocs: Updating GOMAXPROCS=8: determined from CPU quota
panic: runtime error: invalid memory address or nil pointer dereference
```
Will test in a sample service.

maxprocs: Print newline after log

---

filewatcher/filewatcher.go
filewatcher/filewatcher_test.go
secrets/store.go
secrets/store_test.go

When we added support for CSI directories, we introduced a bug that we no longer wait for secrets.json to become available, because os.Stat call would fail with file not exist error immediately.
Since in CSI directories case the directory would be guaranteed to be available immediately (unlike the vault case), assume file not exist errors from os.Stat as using file instead of directory, and let filewatcher.New to handle the waiting as before. Also add a test for it.
While I'm here, also remove the usages of os.IsNotExist and os.IsExist follow the docs.

secrets: Fix bug about not wait for secrets.json to become available

---

.github/workflows/go-ci.yaml
clientpool/channel.go
clientpool/channel_test.go
clientpool/interface_test.go
drainer.go
ecinterface/global.go
ecinterface/global_test.go
events/events_test.go
filewatcher/filewatcher_test.go
go.mod
httpbp/client_middlewares.go
httpbp/client_middlewares_test.go
internalv2compat/compat.go
kafkabp/consumer.go
kafkabp/consumer_test.go
kafkabp/group_consumer.go
metricsbp/log_test.go
metricsbp/statsd.go
thriftbp/client_pool_test.go
thriftbp/ttl_client_test.go
tracing/tags.go
tracing/tags_test.go

Use the new atomic package API introduced in go 1.19:
* Replace atomic.Value with atomic.Pointer
* Replace atomic.Add*/Store*/Load*/etc. with new Int*/Uint* atomic types
* Except the atomic.Value used in filewatcher, as to take full advantage of that we would need to make breaking API changes to filewatcher

Drop support for go 1.18

---

errorsbp/batch.go
errorsbp/batch_test.go

Go 1.20 is going to add native support for batched/multi errors, and we will be able to eventually deprecate errorsbp.Batch, but we can only do so after we dropped support for go 1.19.
Before that, make errorsbp.Batch play nicer with go 1.20 by:
* Implement the new `Unwrap() []error` optional interface.
* Make errorsbp.BatchSize also support other errors implementing the new optional interface.

errorsbp: Update for go 1.20

---

thriftbp/server.go
thriftbp/server_middlewares.go

This was already done in httpbp. Without this, middlewares after it will get nil error when panic happens, which can result in inaccurate/misleading metrics or other bugs.
To do so:
* Mark the old RecoverPanic middleware as deprecated
* Unexport RecoverPanik to recoverPanik. This is a breaking change, but RecoverPanik was only added in beta releases, it's not in v0.9.11.

thriftbp: Force recoverPanik to be the last server middleware

---

thriftbp/client_pool.go
thriftbp/prometheus.go

We did some work previously to try to move dns out of hot path as much as possible in thrift client pool, by doing background refreshes, etc.. But there are always a (hopefully small) portion of client calls would still do dns on hot path, and we lack observability into how often that actually happens.
To get the precise data would require some breaking changes to clientpool package (to pass in required prometheus labels), so adding a counter to the opener call instead, which is the next best thing, as in we only need to ignore the spikes when a new pod comes up and need to fill in the initial clients when initialize a client pool.

thriftbp: Add a counter for opener calls in client pool

---

httpbp/prometheus.go

Current buckets are defined to be the same as the latency buckets, which don't go above ~15. While this works in the context of `seconds`, it doesn't work well for `bytes`. Those new buckets should allow us to track a wide range of request/response sizes.

Make the HTTP size buckets usable

---

.github/workflows/go-ci.yaml
secrets/secrets.go

There's a new security warning from git suddenly started to appear
today, add a workaround to it (see [1]).
Also seems the newer version of staticcheck starts to complain a new
part of the code that's legit, so fix that as well.
[1]: https://github.com/actions/runner-images/issues/6775

Fix github actions

---

tracing/config.go

Currently tracing.InitFromConfig, which is called from baseplate.New, auto registers ErrorReporterCreateServerSpanHook. With the prometheus metrics we already have very good visibility on the errors happened on thrift/grpc/http servers, and those additional sentry reports mostly just adds noise and cost without being useful. Also in the current setup there's not really an easy way for service owners to unregister ErrorReporterCreateServerSpanHook after they called baseplate.New.
As a result, flip it to opt-in. If a service really want it, they can register it themselves in their main function, after baseplate.New call.

tracing: Do not auto register ErrorReporterCreateServerSpanHook

---

errorsbp/batch.go
errorsbp/batch_test.go

This replaces errorsbp.Batch.AddPrefix for services already on go 1.20
to migrate from errorsbp.Batch to errors.Join, and help our eventual
deprecation of errorsbp.Batch when we drop support to go 1.19.
Currently a typical use case with errorsbp.Batch is like this:
var batch errorsbp.Batch
...
for _, work := range works {
batch.AddPrefix(work.Name(), work.Do())
}
...
return batch.Compile()
With this change and go 1.20, they would change the code to something
like this:
var errs []error
...
for _, work := range works {
errs = append(errs, errorsbp.Prefix(work.Name(), work.Do()))
}
...
return errors.Join(errs)
Without this change, they would need to add extra ifs to avoid producing
non-nil error if nothing failed:
var errs []error
...
for _, work := range works {
if err := work.Do(); err != …

errorsbp: Add Prefix

---

clientpool/channel.go
clientpool/channel_test.go
thriftbp/client_pool.go
thriftbp/client_pool_test.go

The only reason the constructor in clientpool would return both non-nil Pool and error is to avoid making breaking changes. Since we already made a breaking change in 6f97656, it's better to always return nil Pool when returning an error.
Also fix %w used in logging, and add doccomment to the newly added functions in thriftbp.

clientpool: Follow up on 6f97656

---

kafkabp/config.go
kafkabp/consumer.go
kafkabp/consumer_test.go

Currently when using non-group consumers, they always consume all
partitions from the topic.
This newly added ConsumePartitionFuncProvider allows the services to
optionally only consume from the partitions they are interested in. This
allows hugely reduced network traffic between the consumers and the
brokers when the service only need a subset of the partitions (for
example, the service itself is already sharded and the sharding is
aligned on kafka partitions).

kafkabp: Add ConsumePartitionFuncProvider to non-group consumers

---

kafkabp/config.go
kafkabp/prometheus.go

There are certain kafka features requiring a minimal configured version to work, so this gauge can provide us visibility on whether we have consumers configured on lower version (or didn't configure it and use the default version) before we enable those features to avoid production outage.

kafkabp: Add a gauge to report configured version

---

internal/admin/server.go

Still fallback to 6060 by default.

admin: Get port from $BASEPLATE_SIDECAR_ADMIN_PORT

---

baseplate.go

When a baseplate server is shutting down in k8s
* baseplate calls func (srv *Server) Shutdown(ctx context.Context) error which does the following:
* Shutdown works by first closing all open listeners
* k8s is attempting to remove the endpoint for the endpoints group and thus make (new) incoming traffic to the pod 0
This is a race condition because some callers are still trying to connect. We have empirically seen that the 5 second default is good enough for most services.

feat: Improve shutdown Delay default

---

.github/workflows/go-ci.yaml
httpbp/middlewares.go
httpbp/prometheus.go
kafkabp/consumer.go
kafkabp/prometheus.go
thriftbp/client_pool.go
thriftbp/prometheus.go
thriftbp/server_middlewares.go

1. Change some of the references to statsd metrics in doc comments to prometheus metrics.
2. Remove the deprecated prometheus metrics/labels from the previous release.
While I'm here, also add go 1.20 to CI.

Metrics cleanup

---

httpbp/client_middlewares.go
httpbp/prometheus.go
httpbp/prometheus_test.go
internal/prometheusbpint/spectest/spec.go
internal/prometheusbpint/spectest/spec_test.go

This PR adds labels for prom metrics to match baseplate spec and updates metrics documentation where relevant. 
[Design Doc]()
1. `http_server_time_to_first_byte_seconds` -- description is incorrect. Should be “Time elapsed before first byte was sent". 
2. `http_client_latency_seconds` -- adds missing http_endpoint label
3. `http_client_requests_total` -- adds missing http_endpoint label
4. `http_client_active_requests` -- adds missing http_endpoint label 
[Jira]()

Update prom metrics to match baseplate spec

---

log/version.go

Make this as the last fallback.
This helps reproducible docker image builds from monorepos, as env var can be stamped from k8s yaml and totally outside of the docker image (so we can keep the docker image intact when no other changes is in the service's dependency tree).

log: Also stamp version from env var

---

experiments/experiments.go

In the effort to migrate more services to new Decider experiments SDK, the old baseplate Experiments code is being marked deprecated.
Added prometheus counters since last review, to track any services still using old package.
[Jira](https://reddit.atlassian.net/browse/EX-608)

[EX-608] Depracate experiments

---

secrets/store.go
secrets/testing.go

Guard secrets.Store middleware with a mutex to make adding new middlewares to an existing store threadsafe.
Sometimes we have to call `AddMiddleware` in a goroutine which can lead to race conditions with other calls to `AddMiddleware`. Adding a mutex around updating and calling the middleware functions protects us from this.

make secrets.Store middleware threadsafe

---

internalv2compat/compat.go
tracing/tracer.go

In baseplate.go v2 we configure a global opentracing tracer. Currently, calling `baseplate.New` will override the new tracer. This change prevents the override using a flag in `internalv2compat`.
If `internalv2compat.SetV2TracingEnabled(true)` is called before `InitGlobalTracer`, the opentracing global tracer will not be configured, and a message will be logged.

tracing: skip reconfiguration if tracer already configured

---

httpbp/client_middlewares.go
httpbp/middlewares.go
httpbp/server.go
internalv2compat/compat.go
thriftbp/client_middlewares.go
thriftbp/server_middlewares.go

Adds hooks for overriding tracing middleware.

V2 middleware injection

---

thriftbp/client_pool.go
thriftbp/client_pool_test.go

We now have a generic ingress for thrift traffic that routes the traffic based on a header. This means that looking at a service config we don't see what service the traffic is going to and that the application need to set the header manually unlike every other configuration bit.
So this PR adds a new configuration to set this header.
[Design Doc]()
[Jira]()

Add config for the header use by the general ingress

---

kafkabp/consumer.go

We occasionally have cases that services need to set some sarama config
that's not supported by kafkabp.ConsumerConfig, and there's currently no
way for them to do that besides forking kafkabp code locally. Provide
this as an escape hatch for easier iteration.

kafkabp: Add NewConsumerWithConfigOverriders

---

internal/thriftint/baseplate_error.go

The next thrift release, 0.20.0, will add slog.LogValuer for all thrift generated errors [1] [2]. This prepares us so that WrapBaseplateError will keep the implementation if it's available to be used with slog.
This also drops support to go 1.20. 1.22 is already at rc2 today so I think it's time to do that.
[1]: https://github.com/apache/thrift/pull/2884
[2]: https://issues.apache.org/jira/browse/THRIFT-5745

thriftbp: Support native slog.LogValuer implementation for errors

---

httpbp/client_middlewares.go
httpbp/client_middlewares_test.go

When we set GetBody in http.Request, it's expected that Body is also
set, add special handling in Retries to make sure we also set Body when
retrying when GetBody is also set before each retry attempt.
Also always clone the request before each retry attempt to avoid some
subtle errors, and skip the Retries middleware altogether if Body is set
but GetBody is not.

httpbp: Fix Retries middleware

---

thriftbp/client_pool.go
thriftbp/client_pool_test.go

Also update thrifttest to use UDS when possible.

thriftbp: Support unix domain socket on thrift clients

---

thriftbp/client_pool.go

Due to a bad merge between the previous 2 PRs, we are not really using the countingDelegateTransport in the client created by client pool, so the bytes are not counting and we always report 0 as the bytes read/written.
Rename the args inside newClient generator to fix the bug.

thriftbp: Fix a bug caused by bad merge from the previous PR

---

thriftbp/server.go

We marked
DefaultProcessorMiddlewaresArgs.ReportPayloadSizeMetricsSampleRate as deprecated in a previous PR, but forgot to also mark ServerConfig.ReportPayloadSizeMetricsSampleRate as deprecated.

thriftbp: Deprecate ServerConfig.ReportPayloadSizeMetricsSampleRate

---

experiments/experiments.go

Note: secrets package is not switching because filewatcher.MockFileWatcher is part of its API so switching to v2 will be a breaking change for secrets package.

experiments: Switch to filewatcher/v2

---

clientpool/channel.go
clientpool/interface_test.go

Currently, when Get is Called after Close, we'll just get a nil client from the pool and the next `c.IsOpen` check will just panic, which makes it very hard to debug why. Add a check to return an appropriate error.

clientpool: Check Get after Close and return appropriate error

---

kafkabp/rack.go

Also modernize the code a bit (use sync.OnceValues, etc.).

kafkabp: Support AWS IMDS v2 for rack id

---

filewatcher/filewatcher.go
log/wrapper.go
log/wrapper_test.go
thriftbp/client_pool.go

Also implement log.Wrapper.MarshalYAML for nil values.
Also add `yaml:"-"` explicitly for config struct fields that's not yaml-unmarshal-able.

Add omitempty yaml tag to deprecated log.Wrapper fields

---

redis/cache/redispipebp/monitored.go
redis/db/redisbp/hooks.go
redis/db/redisbp/hooks_test.go
redis/db/redisbp/monitored_client.go
redis/internal/redisprom/requests.go

This adds a new cluster label to client metrics. This can be used to join the client metrics with the cluster metrics in prometheus based dashboards.
We set the cluster label only if we can determine it from the address, otherwise it remains an empty string.

Support attributing client metrics back to the owning cluster

---

httpbp/client_middlewares.go
httpbp/client_middlewares_test.go
httpbp/fixtures_test.go
httpbp/middlewares.go
httpbp/middlewares_test.go
httpbp/server_test.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/server_middlewares.go
thriftbp/server_middlewares_test.go

For the following 3 tracing middlewares:
- thriftbp server
- thriftbp client
- httpbp client
The current behavior is to short-circuit to v2 compat middleware if injected, or fallback to v0 tracing implementation if not injected. Change the fallback logic to no-op, as the v0 tracing implementation is not really working any more and it will spam logs.
For httpbp server tracing middleware, remove it from defaults, as the current v2 compat implementation is to skip it when injected as the API is not sufficient for the v2 compat implementation to work.
This replaces and closes https://github.com/reddit/baseplate.go/pull/664.

httpbp/thriftbp: Tracing middlewares v2 compat fix

---

thriftbp/client_pool.go

Only exceptions defined in thrift IDL is safe for reuse (getting them means the roundtrip is done fully and the response is read fully). All other errors have different degree of risks for reusing.

thriftbp: Tweak client pool connection reuse logic

---

httpbp/client_middlewares.go
httpbp/client_middlewares_test.go
httpbp/faults.go
internal/faults/faults.go
internal/faults/faults_test.go
internal/faults/headers.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/client_pool.go
thriftbp/faults.go

NOTE: This is a refactor of the approved PR https://github.com/reddit/baseplate.go/pull/666 based on offline feedback. In addition to being a refactor, this also moves the fault injection middleware to be the final middleware for each protocol, as it is meant to simulate the upstream service being unavailable.
This PR introduces client-side fault injection capability to HTTP and Thrift clients. The behavior is controlled via new `X-Bp-Fault` headers, and does nothing if they aren't present, are invalid, or don't match the outgoing request.
If clients are currently passing matching `X-Bp-Fault` headers around and they happen to be valid according to this change, then unintended fault injection could take place. This is extremely unlikely to occur given how specific the headers and their …

[REFACTORED] Add support for Thrift and HTTP client-side fault injection.

---

internal/faults/faults.go

These logs need to be removed at least until they are properly rate limited as they trigger on every request.

Remove noisy logs.

---

tracing/finish_option.go

Removing context from the LogRecords fields, to restrict to fields being intentionally added instead of indirectly via context data.

remove ctx from trace log records

---

internalv2compat/compat.go
thriftbp/client_middlewares.go

Closes # 
Services transitioning to baseplate v2 have the service name missing from client traces. Right now its defaulting to `unknown` due to the interop library initializing a global tracer. This is the first change needed to resolve this bug. It is backwards compatible and allows us to rollout the fix gracefully.
More details in internal obs thread.
[Design Doc]()
[Jira]()

bug fix for passing thrift client name in interop

---

headerbp/headerbp.go
headerbp/signing.go
httpbp/client_middlewares.go
httpbp/config.go
httpbp/middlewares.go
httpbp/server_test.go
thriftbp/server_middlewares.go

We ran into some issues trying to rely just on the X-Rddt-Untrusted header being set on ingress and are switching over to having a signature on these headers for HTTP requests.
This does include some small breaking changes, but this had not been rolled out to any services yet.

add headerbp signature validation/minting

---

.github/workflows/go-ci.yaml
go.mod
internal/admin/server_test.go

- Update go.mod to require 1.23+
- Update CI to run on go 1.23 & 1.24

Update for go 1.24

---

thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/server_test.go

There seems to be something wrong with this where it's picking up headers that are being forwarded as ones that are being manually set by the caller.

remove the thrift headerbp client middleware from defaults

---

headerbp/headerbp.go
headerbp/metrics.go
httpbp/client_middlewares.go
httpbp/server_test.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go
thriftbp/server_test.go

After some investigation, we figured out that the cause of the error we encountered was due to the service wiring up the default client middleware manually and using the `NewBaseplateThriftPool` constructor, resulting in the default middleware running twice. This means that on the first pass, the middleware would add the header to the request. The second pass would then see this and fail the request. I made two changes to make this safer:
1. Added an idempotency check to the client middleware so it only runs once per call. Add an error log and a metric when we detect this happening.
2. Changed the client middlewares to instead drop new baseplate headers and log an error message rather than failing the call.

Make headerbp client middleware safer

---

thriftbp/client_middlewares.go
thriftbp/server_test.go

This is really just to make the code cleaner since it _technically_ works because `thrift.GetWriteHeaderList` returns the underlying list, not a copy, and `slices.Delete` deletes from the source slice. I think the code is a lot clearer and less likely to have a bug later if we always set the outgoing header list.
I verified this by adding a test case. The test passes without my changes, but it fails if I copy `outgoing` before deleting the headers from it.

always update thrift header write list in headerbp client middleware

---

httpbp/config.go
log/sentry.go
metricsbp/config.go
thriftbp/client_pool.go

By default, if we marshal a map or slice from nil into yaml, then back into the map/slice, the value will not be the same!
Without omitempty, we marshal nil into the emptyval, then emptyval as is back into the struct. It is not a known guarantee for users that nil == empty.

omitempty for tags that marshal into zero val but should be nil

---

log/core_wrapper.go

Sample latencies while testing locally with a skeleton baseplate app:
```
baseplate_log_latency_seconds_bucket{le="5e-06"} 1287
baseplate_log_latency_seconds_bucket{le="1e-05"} 1513
baseplate_log_latency_seconds_bucket{le="5e-05"} 1531
baseplate_log_latency_seconds_bucket{le="0.0001"} 1534
baseplate_log_latency_seconds_bucket{le="0.0005"} 1535
baseplate_log_latency_seconds_bucket{le="0.001"} 1535
baseplate_log_latency_seconds_bucket{le="0.005"} 1535
baseplate_log_latency_seconds_bucket{le="0.01"} 1535
baseplate_log_latency_seconds_bucket{le="0.05"} 1535
baseplate_log_latency_seconds_bucket{le="0.1"} 1535
baseplate_log_latency_seconds_bucket{le="0.5"} 1535
baseplate_log_latency_seconds_bucket{le="1"} 1535
baseplate_log_latency_seconds_bucket{le="+Inf"} 1538 …
```

Add a prometheus metric for logging latency

---

log/core_wrapper.go

The new name makes it clear that this captures the duration of local logging calls as opposed to end-to-end logging latency to a centralized collector.

Rename baseplate_log_latency_seconds to baseplate_log_write_duration_seconds

---

filewatcher/v2/filewatcher.go
filewatcher/v2/filewatcher_test.go
go.mod
go.sum
secrets/store_internal_test.go

Works around the bug https://github.com/fsnotify/fsnotify bug 652 (not linking to avoid creating xref)
Note that the bug above **only reproduces on Linux**, which makes it fun to reproduce.
```
❯ docker run --rm -it \
-v "$(pwd)":/app \
-w /app \
golang:1 \
go test ./filewatcher/v2 -test.v
```
can be used to test / reproduce it on Mac OS.

Upgrade fsnotify and install a workaround for fsnotify/v2

---

httpbp/client_middlewares.go
internal/faults/faults.go
internal/faults/faults_test.go
thriftbp/client_middlewares.go

In-path parameters were causing this label to explode in cardinality. Until a better solution is worked out, we will drop that label value entirely for HTTP requests. This PR updates the `Inject` function to take in both a `method` and `methodLabel` parameter, since while we don't want to output the label, we do still want the method to be available for matching against the fault configuration in case a very specific fault is desired. Note that matching against all methods is unchanged by just not including a method to match against in the fault configuration, as was always the case. The parameter list was additionally updated to be a struct as it was getting long and unwieldy.

Use empty string as the fault metric method label for HTTP requests.

---

internalv2compat/compat.go
thriftbp/client_middlewares.go
thriftbp/server.go
thriftbp/server_middlewares.go
thriftbp/server_test.go

Closes # 
Right now server trace spans for thrift report the service name as unknown. Because the thrift compiler doesn't generate schema metadata, we can fallback to relying on compiler conventions to source the service name defined in the schema.
[Design Doc]()
[Jira]()

add support for thrift service name in server traces

---

randbp/jitter.go
randbp/jitter_test.go
randbp/rand.go
randbp/sample.go
randbp/string.go
randbp/string_example_test.go
randbp/string_test.go

Switch all usage of R to the global PRNG from stdlib math/rand/v2 instead.
Don't officially mark it as deprecated as that will break a lot of existing code, and it's still ok to use (same as in stdlib math/rand is still ok to use).

randbp: Comment R as deprecated

---

internal/faults/faults_test.go
internal/faults/headers.go
internal/faults/headers_test.go

Do not allow matching when the configuration is for a specific method and the real method is unknown.
The main idea here is that if someone wanted to inject a fault on the `foobar` method, a request with an unknown method should not also have that fault injected just because the primary address matched.
Note that this has already been merged into bpv2 and this PR is just to get bpv0 on the same page. This will be followed by another PR getting bpv0 up to sync as well.

[Faults] Require a strict method match when `m` is provided.

---

httpbp/client_middlewares.go
httpbp/client_middlewares_test.go
internal/faults/faults.go
internal/faults/faults_test.go
internal/faults/headers.go
internal/faults/headers_test.go
internal/faults/metrics/metrics.go
thriftbp/client_middlewares.go
thriftbp/client_middlewares_test.go

The PRs adding this to bpv2 have already been approved, and this PR is just to get bpv0 up-to-date with those.
This introduces support for a new `h` parameter in the fault configuration header value. Specifically, if the `h` parameter is present, then the value of it will be checked against the host/authority header of the outgoing request before determining whether the request matches for fault injection.
Note that this is _not_ supported for gRPC due to the authority header not being exposed by client-middleware runtime. If you'd like more info on the workaround for gRPC, I'm happy to DM information on what we plan to do.

[Faults] Add support for matching on the host/authority header.

---

events/doc.go
events/events.go

This PR puts the `events` package in maintenance mode and adds deprecation warnings to discourage new usage. 
[Decision Doc](https://docs.google.com/document/d/1SzbXzvSJlW_A7UxwrS4-41RmX43iLjryyu0A2pRaP20/edit?tab=t.0)
[Jira](https://reddit.atlassian.net/browse/DATAPIPE-303)

Deprecate events package in favor of GRPC Event Collector
